version: '3.5'

services:
  db:
    container_name: ${SERVICE_NAME}_db
    restart: always
    image: postgres:latest
    volumes:
      - ./.docker/data/postgres:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    networks:
      - backend
  service:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: ${SERVICE_NAME}_service
    ports:
      - '${HTTP_PORT}:8000'
      - '${GRPC_PORT}:9000'
    networks:
      - backend
    volumes:
      - ./configs:/data/conf
    restart: unless-stopped
    depends_on:
      - db
    profiles:
      - build
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

networks:
  backend:
    name: backend
    external: true
