// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: api/rbac/v1/assigns.proto

package rbac_v1

import (
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssignRoleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityId string    `protobuf:"bytes,1,opt,name=identityId,proto3" json:"identityId,omitempty"`
	RoleId     int64     `protobuf:"varint,2,opt,name=roleId,proto3" json:"roleId,omitempty"`
	TeamId     int64     `protobuf:"varint,3,opt,name=teamId,proto3" json:"teamId,omitempty"`
	Resource   *Resource `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *AssignRoleRequest) Reset() {
	*x = AssignRoleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRoleRequest) ProtoMessage() {}

func (x *AssignRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRoleRequest.ProtoReflect.Descriptor instead.
func (*AssignRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{0}
}

func (x *AssignRoleRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *AssignRoleRequest) GetRoleId() int64 {
	if x != nil {
		return x.RoleId
	}
	return 0
}

func (x *AssignRoleRequest) GetTeamId() int64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *AssignRoleRequest) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type AssignRolesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Assigns []*AssignRoleRequest `protobuf:"bytes,1,rep,name=assigns,proto3" json:"assigns,omitempty"`
}

func (x *AssignRolesRequest) Reset() {
	*x = AssignRolesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRolesRequest) ProtoMessage() {}

func (x *AssignRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRolesRequest.ProtoReflect.Descriptor instead.
func (*AssignRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{1}
}

func (x *AssignRolesRequest) GetAssigns() []*AssignRoleRequest {
	if x != nil {
		return x.Assigns
	}
	return nil
}

type AssignRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignId int64 `protobuf:"varint,1,opt,name=assignId,proto3" json:"assignId,omitempty"`
}

func (x *AssignRequest) Reset() {
	*x = AssignRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignRequest) ProtoMessage() {}

func (x *AssignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignRequest.ProtoReflect.Descriptor instead.
func (*AssignRequest) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{2}
}

func (x *AssignRequest) GetAssignId() int64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

type ListAssignsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdentityIds []string `protobuf:"bytes,3,rep,name=identityIds,proto3" json:"identityIds,omitempty"`
	// Types that are assignable to Field:
	//
	//	*ListAssignsRequest_Filter
	//	*ListAssignsRequest_Resource
	Field isListAssignsRequest_Field `protobuf_oneof:"field"`
}

func (x *ListAssignsRequest) Reset() {
	*x = ListAssignsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignsRequest) ProtoMessage() {}

func (x *ListAssignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignsRequest.ProtoReflect.Descriptor instead.
func (*ListAssignsRequest) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{3}
}

func (x *ListAssignsRequest) GetIdentityIds() []string {
	if x != nil {
		return x.IdentityIds
	}
	return nil
}

func (m *ListAssignsRequest) GetField() isListAssignsRequest_Field {
	if m != nil {
		return m.Field
	}
	return nil
}

func (x *ListAssignsRequest) GetFilter() *ResourceFilter {
	if x, ok := x.GetField().(*ListAssignsRequest_Filter); ok {
		return x.Filter
	}
	return nil
}

func (x *ListAssignsRequest) GetResource() *Resource {
	if x, ok := x.GetField().(*ListAssignsRequest_Resource); ok {
		return x.Resource
	}
	return nil
}

type isListAssignsRequest_Field interface {
	isListAssignsRequest_Field()
}

type ListAssignsRequest_Filter struct {
	Filter *ResourceFilter `protobuf:"bytes,5,opt,name=filter,proto3,oneof"`
}

type ListAssignsRequest_Resource struct {
	Resource *Resource `protobuf:"bytes,4,opt,name=resource,proto3,oneof"`
}

func (*ListAssignsRequest_Filter) isListAssignsRequest_Field() {}

func (*ListAssignsRequest_Resource) isListAssignsRequest_Field() {}

type ResourceFilter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ResourceTypes []string `protobuf:"bytes,1,rep,name=resourceTypes,proto3" json:"resourceTypes,omitempty"`
}

func (x *ResourceFilter) Reset() {
	*x = ResourceFilter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceFilter) ProtoMessage() {}

func (x *ResourceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceFilter.ProtoReflect.Descriptor instead.
func (*ResourceFilter) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceFilter) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

type ListAssignsReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Roles []*AssignedRole `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *ListAssignsReply) Reset() {
	*x = ListAssignsReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAssignsReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAssignsReply) ProtoMessage() {}

func (x *ListAssignsReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAssignsReply.ProtoReflect.Descriptor instead.
func (*ListAssignsReply) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{5}
}

func (x *ListAssignsReply) GetRoles() []*AssignedRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type AssignedRole struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AssignId   int64     `protobuf:"varint,4,opt,name=assignId,proto3" json:"assignId,omitempty"`
	Role       *Role     `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	IdentityId *string   `protobuf:"bytes,2,opt,name=identityId,proto3,oneof" json:"identityId,omitempty"`
	Resource   *Resource `protobuf:"bytes,5,opt,name=resource,proto3,oneof" json:"resource,omitempty"`
}

func (x *AssignedRole) Reset() {
	*x = AssignedRole{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_rbac_v1_assigns_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AssignedRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignedRole) ProtoMessage() {}

func (x *AssignedRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_rbac_v1_assigns_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignedRole.ProtoReflect.Descriptor instead.
func (*AssignedRole) Descriptor() ([]byte, []int) {
	return file_api_rbac_v1_assigns_proto_rawDescGZIP(), []int{6}
}

func (x *AssignedRole) GetAssignId() int64 {
	if x != nil {
		return x.AssignId
	}
	return 0
}

func (x *AssignedRole) GetRole() *Role {
	if x != nil {
		return x.Role
	}
	return nil
}

func (x *AssignedRole) GetIdentityId() string {
	if x != nil && x.IdentityId != nil {
		return *x.IdentityId
	}
	return ""
}

func (x *AssignedRole) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_api_rbac_v1_assigns_proto protoreflect.FileDescriptor

var file_api_rbac_v1_assigns_proto_rawDesc = []byte{
	0x0a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x72, 0x62, 0x61,
	0x63, 0x2e, 0x76, 0x31, 0x1a, 0x19, 0x61, 0x70, 0x69, 0x2f, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x18, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64,
	0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x92, 0x01, 0x0a, 0x11, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x72, 0x6f, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x74, 0x65, 0x61, 0x6d, 0x49, 0x64, 0x12,
	0x2d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x11, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x4a,
	0x0a, 0x12, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x07, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x22, 0x2b, 0x0a, 0x0d, 0x41, 0x73,
	0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20,
	0x0a, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x73,
	0x12, 0x31, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x17, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x12, 0x2f, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x48, 0x00, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x42, 0x07, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x22, 0x36, 0x0a,
	0x0e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12,
	0x24, 0x0a, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x73, 0x22, 0x3f, 0x0a, 0x10, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73,
	0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2b, 0x0a, 0x05, 0x72, 0x6f, 0x6c,
	0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e,
	0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x52,
	0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73, 0x22, 0xc2, 0x01, 0x0a, 0x0c, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x65, 0x64, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x49, 0x64, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x6f, 0x6c, 0x65,
	0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12, 0x23, 0x0a, 0x0a, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69,
	0x74, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0a, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x88, 0x01, 0x01, 0x12, 0x32, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x48, 0x01, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x88, 0x01, 0x01, 0x42,
	0x0d, 0x0a, 0x0b, 0x5f, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x64, 0x42, 0x0b,
	0x0a, 0x09, 0x5f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x32, 0x90, 0x02, 0x0a, 0x07,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x3e, 0x0a, 0x0a, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x1a, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e,
	0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x40, 0x0a, 0x0b, 0x41, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x12, 0x1b, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6d, 0x70, 0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3c, 0x0a, 0x0c, 0x55, 0x6e, 0x61,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x16, 0x2e, 0x72, 0x62, 0x61, 0x63,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x14, 0x2e, 0x75, 0x74, 0x69, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x45, 0x0a, 0x0b, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x12, 0x1b, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31,
	0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x45,
	0x0a, 0x07, 0x72, 0x62, 0x61, 0x63, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x38, 0x67, 0x69, 0x74,
	0x6c, 0x61, 0x62, 0x2e, 0x63, 0x61, 0x6c, 0x65, 0x6e, 0x64, 0x61, 0x72, 0x69, 0x61, 0x2e, 0x74,
	0x65, 0x61, 0x6d, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x72, 0x62, 0x61,
	0x63, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x72, 0x62, 0x61, 0x63, 0x2f, 0x76, 0x31, 0x3b, 0x72, 0x62,
	0x61, 0x63, 0x5f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_rbac_v1_assigns_proto_rawDescOnce sync.Once
	file_api_rbac_v1_assigns_proto_rawDescData = file_api_rbac_v1_assigns_proto_rawDesc
)

func file_api_rbac_v1_assigns_proto_rawDescGZIP() []byte {
	file_api_rbac_v1_assigns_proto_rawDescOnce.Do(func() {
		file_api_rbac_v1_assigns_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_rbac_v1_assigns_proto_rawDescData)
	})
	return file_api_rbac_v1_assigns_proto_rawDescData
}

var file_api_rbac_v1_assigns_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_rbac_v1_assigns_proto_goTypes = []interface{}{
	(*AssignRoleRequest)(nil),  // 0: rbac.v1.AssignRoleRequest
	(*AssignRolesRequest)(nil), // 1: rbac.v1.AssignRolesRequest
	(*AssignRequest)(nil),      // 2: rbac.v1.AssignRequest
	(*ListAssignsRequest)(nil), // 3: rbac.v1.ListAssignsRequest
	(*ResourceFilter)(nil),     // 4: rbac.v1.ResourceFilter
	(*ListAssignsReply)(nil),   // 5: rbac.v1.ListAssignsReply
	(*AssignedRole)(nil),       // 6: rbac.v1.AssignedRole
	(*Resource)(nil),           // 7: rbac.v1.Resource
	(*Role)(nil),               // 8: rbac.v1.Role
	(*v1.EmptyReply)(nil),      // 9: utils.v1.EmptyReply
}
var file_api_rbac_v1_assigns_proto_depIdxs = []int32{
	7,  // 0: rbac.v1.AssignRoleRequest.resource:type_name -> rbac.v1.Resource
	0,  // 1: rbac.v1.AssignRolesRequest.assigns:type_name -> rbac.v1.AssignRoleRequest
	4,  // 2: rbac.v1.ListAssignsRequest.filter:type_name -> rbac.v1.ResourceFilter
	7,  // 3: rbac.v1.ListAssignsRequest.resource:type_name -> rbac.v1.Resource
	6,  // 4: rbac.v1.ListAssignsReply.roles:type_name -> rbac.v1.AssignedRole
	8,  // 5: rbac.v1.AssignedRole.role:type_name -> rbac.v1.Role
	7,  // 6: rbac.v1.AssignedRole.resource:type_name -> rbac.v1.Resource
	0,  // 7: rbac.v1.Assigns.AssignRole:input_type -> rbac.v1.AssignRoleRequest
	1,  // 8: rbac.v1.Assigns.AssignRoles:input_type -> rbac.v1.AssignRolesRequest
	2,  // 9: rbac.v1.Assigns.UnassignRole:input_type -> rbac.v1.AssignRequest
	3,  // 10: rbac.v1.Assigns.ListAssigns:input_type -> rbac.v1.ListAssignsRequest
	9,  // 11: rbac.v1.Assigns.AssignRole:output_type -> utils.v1.EmptyReply
	9,  // 12: rbac.v1.Assigns.AssignRoles:output_type -> utils.v1.EmptyReply
	9,  // 13: rbac.v1.Assigns.UnassignRole:output_type -> utils.v1.EmptyReply
	5,  // 14: rbac.v1.Assigns.ListAssigns:output_type -> rbac.v1.ListAssignsReply
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_rbac_v1_assigns_proto_init() }
func file_api_rbac_v1_assigns_proto_init() {
	if File_api_rbac_v1_assigns_proto != nil {
		return
	}
	file_api_rbac_v1_models_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_rbac_v1_assigns_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRoleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRolesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssignsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceFilter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAssignsReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_rbac_v1_assigns_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AssignedRole); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_rbac_v1_assigns_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ListAssignsRequest_Filter)(nil),
		(*ListAssignsRequest_Resource)(nil),
	}
	file_api_rbac_v1_assigns_proto_msgTypes[6].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_rbac_v1_assigns_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_rbac_v1_assigns_proto_goTypes,
		DependencyIndexes: file_api_rbac_v1_assigns_proto_depIdxs,
		MessageInfos:      file_api_rbac_v1_assigns_proto_msgTypes,
	}.Build()
	File_api_rbac_v1_assigns_proto = out.File
	file_api_rbac_v1_assigns_proto_rawDesc = nil
	file_api_rbac_v1_assigns_proto_goTypes = nil
	file_api_rbac_v1_assigns_proto_depIdxs = nil
}
