// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: api/rbac/v1/assigns.proto

package rbac_v1

import (
	context "context"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	TeamIdentityRole_AssignRole_FullMethodName   = "/rbac.v1.TeamIdentityRole/AssignRole"
	TeamIdentityRole_DeleteAssign_FullMethodName = "/rbac.v1.TeamIdentityRole/DeleteAssign"
	TeamIdentityRole_ListAssigns_FullMethodName  = "/rbac.v1.TeamIdentityRole/ListAssigns"
)

// TeamIdentityRoleClient is the client API for TeamIdentityRole service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeamIdentityRoleClient interface {
	AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	DeleteAssign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error)
	ListAssigns(ctx context.Context, in *ListAssignsRequest, opts ...grpc.CallOption) (*ListAssignsReply, error)
}

type teamIdentityRoleClient struct {
	cc grpc.ClientConnInterface
}

func NewTeamIdentityRoleClient(cc grpc.ClientConnInterface) TeamIdentityRoleClient {
	return &teamIdentityRoleClient{cc}
}

func (c *teamIdentityRoleClient) AssignRole(ctx context.Context, in *AssignRoleRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, TeamIdentityRole_AssignRole_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamIdentityRoleClient) DeleteAssign(ctx context.Context, in *AssignRequest, opts ...grpc.CallOption) (*v1.EmptyReply, error) {
	out := new(v1.EmptyReply)
	err := c.cc.Invoke(ctx, TeamIdentityRole_DeleteAssign_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamIdentityRoleClient) ListAssigns(ctx context.Context, in *ListAssignsRequest, opts ...grpc.CallOption) (*ListAssignsReply, error) {
	out := new(ListAssignsReply)
	err := c.cc.Invoke(ctx, TeamIdentityRole_ListAssigns_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamIdentityRoleServer is the server API for TeamIdentityRole service.
// All implementations must embed UnimplementedTeamIdentityRoleServer
// for forward compatibility
type TeamIdentityRoleServer interface {
	AssignRole(context.Context, *AssignRoleRequest) (*v1.EmptyReply, error)
	DeleteAssign(context.Context, *AssignRequest) (*v1.EmptyReply, error)
	ListAssigns(context.Context, *ListAssignsRequest) (*ListAssignsReply, error)
	mustEmbedUnimplementedTeamIdentityRoleServer()
}

// UnimplementedTeamIdentityRoleServer must be embedded to have forward compatible implementations.
type UnimplementedTeamIdentityRoleServer struct {
}

func (UnimplementedTeamIdentityRoleServer) AssignRole(context.Context, *AssignRoleRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AssignRole not implemented")
}
func (UnimplementedTeamIdentityRoleServer) DeleteAssign(context.Context, *AssignRequest) (*v1.EmptyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAssign not implemented")
}
func (UnimplementedTeamIdentityRoleServer) ListAssigns(context.Context, *ListAssignsRequest) (*ListAssignsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAssigns not implemented")
}
func (UnimplementedTeamIdentityRoleServer) mustEmbedUnimplementedTeamIdentityRoleServer() {}

// UnsafeTeamIdentityRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeamIdentityRoleServer will
// result in compilation errors.
type UnsafeTeamIdentityRoleServer interface {
	mustEmbedUnimplementedTeamIdentityRoleServer()
}

func RegisterTeamIdentityRoleServer(s grpc.ServiceRegistrar, srv TeamIdentityRoleServer) {
	s.RegisterService(&TeamIdentityRole_ServiceDesc, srv)
}

func _TeamIdentityRole_AssignRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamIdentityRoleServer).AssignRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamIdentityRole_AssignRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamIdentityRoleServer).AssignRole(ctx, req.(*AssignRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamIdentityRole_DeleteAssign_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamIdentityRoleServer).DeleteAssign(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamIdentityRole_DeleteAssign_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamIdentityRoleServer).DeleteAssign(ctx, req.(*AssignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamIdentityRole_ListAssigns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssignsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamIdentityRoleServer).ListAssigns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeamIdentityRole_ListAssigns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamIdentityRoleServer).ListAssigns(ctx, req.(*ListAssignsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeamIdentityRole_ServiceDesc is the grpc.ServiceDesc for TeamIdentityRole service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeamIdentityRole_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rbac.v1.TeamIdentityRole",
	HandlerType: (*TeamIdentityRoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AssignRole",
			Handler:    _TeamIdentityRole_AssignRole_Handler,
		},
		{
			MethodName: "DeleteAssign",
			Handler:    _TeamIdentityRole_DeleteAssign_Handler,
		},
		{
			MethodName: "ListAssigns",
			Handler:    _TeamIdentityRole_ListAssigns_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/rbac/v1/assigns.proto",
}
