// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.2
// - protoc             v4.25.1
// source: api/rbac/v1/roles.proto

package rbac_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
	v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationRolesCreateRole = "/rbac.v1.Roles/CreateRole"
const OperationRolesDeleteRole = "/rbac.v1.Roles/DeleteRole"
const OperationRolesDeleteRolePermission = "/rbac.v1.Roles/DeleteRolePermission"
const OperationRolesGetRole = "/rbac.v1.Roles/GetRole"
const OperationRolesListRolePermissions = "/rbac.v1.Roles/ListRolePermissions"
const OperationRolesListRoles = "/rbac.v1.Roles/ListRoles"
const OperationRolesSetRolePermission = "/rbac.v1.Roles/SetRolePermission"
const OperationRolesUpdateRole = "/rbac.v1.Roles/UpdateRole"

type RolesHTTPServer interface {
	CreateRole(context.Context, *CreateRoleRequest) (*RoleReply, error)
	DeleteRole(context.Context, *DeleteRoleRequest) (*v1.EmptyReply, error)
	DeleteRolePermission(context.Context, *DeleteRolePermissionRequest) (*v1.EmptyReply, error)
	GetRole(context.Context, *GetRoleRequest) (*RoleReply, error)
	ListRolePermissions(context.Context, *ListRolePermissionsRequest) (*RolePermissionsReply, error)
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesReply, error)
	SetRolePermission(context.Context, *SetRolePermissionRequest) (*v1.EmptyReply, error)
	UpdateRole(context.Context, *UpdateRoleRequest) (*RoleReply, error)
}

func RegisterRolesHTTPServer(s *http.Server, srv RolesHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/rbac/roles", _Roles_CreateRole0_HTTP_Handler(srv))
	r.PUT("/v1/rbac/roles/{roleId}", _Roles_UpdateRole0_HTTP_Handler(srv))
	r.DELETE("/v1/rbac/roles/{roleId}", _Roles_DeleteRole0_HTTP_Handler(srv))
	r.GET("/v1/rbac/roles/{roleId}", _Roles_GetRole0_HTTP_Handler(srv))
	r.POST("/v1/rbac/roles/list", _Roles_ListRoles0_HTTP_Handler(srv))
	r.POST("/v1/rbac/roles/{roleId}/permissions", _Roles_SetRolePermission0_HTTP_Handler(srv))
	r.DELETE("/v1/rbac/roles/{roleId}/permissions/{permissionId}", _Roles_DeleteRolePermission0_HTTP_Handler(srv))
	r.POST("/v1/rbac/roles/{roleId}/permissions/list", _Roles_ListRolePermissions0_HTTP_Handler(srv))
}

func _Roles_CreateRole0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesCreateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateRole(ctx, req.(*CreateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_UpdateRole0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in UpdateRoleRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesUpdateRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.UpdateRole(ctx, req.(*UpdateRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_DeleteRole0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesDeleteRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRole(ctx, req.(*DeleteRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_GetRole0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in GetRoleRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesGetRole)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.GetRole(ctx, req.(*GetRoleRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RoleReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_ListRoles0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolesRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesListRoles)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRoles(ctx, req.(*ListRolesRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*ListRolesReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_SetRolePermission0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in SetRolePermissionRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesSetRolePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.SetRolePermission(ctx, req.(*SetRolePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_DeleteRolePermission0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in DeleteRolePermissionRequest
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesDeleteRolePermission)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.DeleteRolePermission(ctx, req.(*DeleteRolePermissionRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*v1.EmptyReply)
		return ctx.Result(200, reply)
	}
}

func _Roles_ListRolePermissions0_HTTP_Handler(srv RolesHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in ListRolePermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		if err := ctx.BindVars(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationRolesListRolePermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.ListRolePermissions(ctx, req.(*ListRolePermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*RolePermissionsReply)
		return ctx.Result(200, reply)
	}
}

type RolesHTTPClient interface {
	CreateRole(ctx context.Context, req *CreateRoleRequest, opts ...http.CallOption) (rsp *RoleReply, err error)
	DeleteRole(ctx context.Context, req *DeleteRoleRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
	DeleteRolePermission(ctx context.Context, req *DeleteRolePermissionRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
	GetRole(ctx context.Context, req *GetRoleRequest, opts ...http.CallOption) (rsp *RoleReply, err error)
	ListRolePermissions(ctx context.Context, req *ListRolePermissionsRequest, opts ...http.CallOption) (rsp *RolePermissionsReply, err error)
	ListRoles(ctx context.Context, req *ListRolesRequest, opts ...http.CallOption) (rsp *ListRolesReply, err error)
	SetRolePermission(ctx context.Context, req *SetRolePermissionRequest, opts ...http.CallOption) (rsp *v1.EmptyReply, err error)
	UpdateRole(ctx context.Context, req *UpdateRoleRequest, opts ...http.CallOption) (rsp *RoleReply, err error)
}

type RolesHTTPClientImpl struct {
	cc *http.Client
}

func NewRolesHTTPClient(client *http.Client) RolesHTTPClient {
	return &RolesHTTPClientImpl{client}
}

func (c *RolesHTTPClientImpl) CreateRole(ctx context.Context, in *CreateRoleRequest, opts ...http.CallOption) (*RoleReply, error) {
	var out RoleReply
	pattern := "/v1/rbac/roles"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRolesCreateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) DeleteRole(ctx context.Context, in *DeleteRoleRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/rbac/roles/{roleId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRolesDeleteRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) DeleteRolePermission(ctx context.Context, in *DeleteRolePermissionRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/rbac/roles/{roleId}/permissions/{permissionId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRolesDeleteRolePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "DELETE", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) GetRole(ctx context.Context, in *GetRoleRequest, opts ...http.CallOption) (*RoleReply, error) {
	var out RoleReply
	pattern := "/v1/rbac/roles/{roleId}"
	path := binding.EncodeURL(pattern, in, true)
	opts = append(opts, http.Operation(OperationRolesGetRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "GET", path, nil, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) ListRolePermissions(ctx context.Context, in *ListRolePermissionsRequest, opts ...http.CallOption) (*RolePermissionsReply, error) {
	var out RolePermissionsReply
	pattern := "/v1/rbac/roles/{roleId}/permissions/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRolesListRolePermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...http.CallOption) (*ListRolesReply, error) {
	var out ListRolesReply
	pattern := "/v1/rbac/roles/list"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRolesListRoles))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) SetRolePermission(ctx context.Context, in *SetRolePermissionRequest, opts ...http.CallOption) (*v1.EmptyReply, error) {
	var out v1.EmptyReply
	pattern := "/v1/rbac/roles/{roleId}/permissions"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRolesSetRolePermission))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}

func (c *RolesHTTPClientImpl) UpdateRole(ctx context.Context, in *UpdateRoleRequest, opts ...http.CallOption) (*RoleReply, error) {
	var out RoleReply
	pattern := "/v1/rbac/roles/{roleId}"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationRolesUpdateRole))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "PUT", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
