// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/roles.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/rbac/ent"
	data "gitlab.calendaria.team/services/rbac/internal/data"
)

// MockRoleRepo is a mock of RoleRepo interface.
type MockRoleRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepoMockRecorder
}

// MockRoleRepoMockRecorder is the mock recorder for MockRoleRepo.
type MockRoleRepoMockRecorder struct {
	mock *MockRoleRepo
}

// NewMockRoleRepo creates a new mock instance.
func NewMockRoleRepo(ctrl *gomock.Controller) *MockRoleRepo {
	mock := &MockRoleRepo{ctrl: ctrl}
	mock.recorder = &MockRoleRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepo) EXPECT() *MockRoleRepoMockRecorder {
	return m.recorder
}

// CreateRole mocks base method.
func (m *MockRoleRepo) CreateRole(ctx context.Context, roleDto data.CreateRoleDto) (*ent.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, roleDto)
	ret0, _ := ret[0].(*ent.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleRepoMockRecorder) CreateRole(ctx, roleDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleRepo)(nil).CreateRole), ctx, roleDto)
}

// DeleteRole mocks base method.
func (m *MockRoleRepo) DeleteRole(ctx context.Context, tenantID, roleID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, tenantID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockRoleRepoMockRecorder) DeleteRole(ctx, tenantID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockRoleRepo)(nil).DeleteRole), ctx, tenantID, roleID)
}

// GetRoleByID mocks base method.
func (m *MockRoleRepo) GetRoleByID(ctx context.Context, tenantID, roleID int64) (*ent.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoleByID", ctx, tenantID, roleID)
	ret0, _ := ret[0].(*ent.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoleByID indicates an expected call of GetRoleByID.
func (mr *MockRoleRepoMockRecorder) GetRoleByID(ctx, tenantID, roleID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoleByID", reflect.TypeOf((*MockRoleRepo)(nil).GetRoleByID), ctx, tenantID, roleID)
}

// GetRolesByID mocks base method.
func (m *MockRoleRepo) GetRolesByID(ctx context.Context, tenantID int64, roleIDs []int64) ([]*ent.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesByID", ctx, tenantID, roleIDs)
	ret0, _ := ret[0].([]*ent.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesByID indicates an expected call of GetRolesByID.
func (mr *MockRoleRepoMockRecorder) GetRolesByID(ctx, tenantID, roleIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesByID", reflect.TypeOf((*MockRoleRepo)(nil).GetRolesByID), ctx, tenantID, roleIDs)
}

// GetRolesList mocks base method.
func (m *MockRoleRepo) GetRolesList(ctx context.Context, tenantID int64, search string) ([]*ent.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesList", ctx, tenantID, search)
	ret0, _ := ret[0].([]*ent.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesList indicates an expected call of GetRolesList.
func (mr *MockRoleRepoMockRecorder) GetRolesList(ctx, tenantID, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesList", reflect.TypeOf((*MockRoleRepo)(nil).GetRolesList), ctx, tenantID, search)
}

// ListRolePermissions mocks base method.
func (m *MockRoleRepo) ListRolePermissions(ctx context.Context, tenantID, roleID int64, appIDs []string) ([]*ent.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolePermissions", ctx, tenantID, roleID, appIDs)
	ret0, _ := ret[0].([]*ent.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolePermissions indicates an expected call of ListRolePermissions.
func (mr *MockRoleRepoMockRecorder) ListRolePermissions(ctx, tenantID, roleID, appIDs interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolePermissions", reflect.TypeOf((*MockRoleRepo)(nil).ListRolePermissions), ctx, tenantID, roleID, appIDs)
}

// ListRolesPermissions mocks base method.
func (m *MockRoleRepo) ListRolesPermissions(ctx context.Context, filter data.FilterRolePermissions) ([]*ent.RolePermission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRolesPermissions", ctx, filter)
	ret0, _ := ret[0].([]*ent.RolePermission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRolesPermissions indicates an expected call of ListRolesPermissions.
func (mr *MockRoleRepoMockRecorder) ListRolesPermissions(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRolesPermissions", reflect.TypeOf((*MockRoleRepo)(nil).ListRolesPermissions), ctx, filter)
}

// RemovePermissionFromRole mocks base method.
func (m *MockRoleRepo) RemovePermissionFromRole(ctx context.Context, tenantID, roleID int64, permission *ent.Permission) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePermissionFromRole", ctx, tenantID, roleID, permission)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemovePermissionFromRole indicates an expected call of RemovePermissionFromRole.
func (mr *MockRoleRepoMockRecorder) RemovePermissionFromRole(ctx, tenantID, roleID, permission interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePermissionFromRole", reflect.TypeOf((*MockRoleRepo)(nil).RemovePermissionFromRole), ctx, tenantID, roleID, permission)
}

// SetRolePermission mocks base method.
func (m *MockRoleRepo) SetRolePermission(ctx context.Context, tenantID, roleID int64, permission *ent.Permission, dto data.CreateRolePermissionDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRolePermission", ctx, tenantID, roleID, permission, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRolePermission indicates an expected call of SetRolePermission.
func (mr *MockRoleRepoMockRecorder) SetRolePermission(ctx, tenantID, roleID, permission, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRolePermission", reflect.TypeOf((*MockRoleRepo)(nil).SetRolePermission), ctx, tenantID, roleID, permission, dto)
}

// UpdateRole mocks base method.
func (m *MockRoleRepo) UpdateRole(ctx context.Context, tenantID, roleID int64, roleDto data.UpdateRoleDto) (*ent.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, tenantID, roleID, roleDto)
	ret0, _ := ret[0].(*ent.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleRepoMockRecorder) UpdateRole(ctx, tenantID, roleID, roleDto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleRepo)(nil).UpdateRole), ctx, tenantID, roleID, roleDto)
}
