// Code generated by MockGen. DO NOT EDIT.
// Source: internal/data/teams.go

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	ent "gitlab.calendaria.team/services/rbac/ent"
	data "gitlab.calendaria.team/services/rbac/internal/data"
	utils_v1 "gitlab.calendaria.team/services/utils/api/utils/v1"
)

// MockTeamsRepo is a mock of TeamsRepo interface.
type MockTeamsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTeamsRepoMockRecorder
}

// MockTeamsRepoMockRecorder is the mock recorder for MockTeamsRepo.
type MockTeamsRepoMockRecorder struct {
	mock *MockTeamsRepo
}

// NewMockTeamsRepo creates a new mock instance.
func NewMockTeamsRepo(ctrl *gomock.Controller) *MockTeamsRepo {
	mock := &MockTeamsRepo{ctrl: ctrl}
	mock.recorder = &MockTeamsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTeamsRepo) EXPECT() *MockTeamsRepoMockRecorder {
	return m.recorder
}

// CountListTeams mocks base method.
func (m *MockTeamsRepo) CountListTeams(ctx context.Context, filter data.TeamsListFilter) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountListTeams", ctx, filter)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountListTeams indicates an expected call of CountListTeams.
func (mr *MockTeamsRepoMockRecorder) CountListTeams(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountListTeams", reflect.TypeOf((*MockTeamsRepo)(nil).CountListTeams), ctx, filter)
}

// CreateTeam mocks base method.
func (m *MockTeamsRepo) CreateTeam(ctx context.Context, dto data.TeamDto) (*ent.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, dto)
	ret0, _ := ret[0].(*ent.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockTeamsRepoMockRecorder) CreateTeam(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockTeamsRepo)(nil).CreateTeam), ctx, dto)
}

// DeleteTeam mocks base method.
func (m *MockTeamsRepo) DeleteTeam(ctx context.Context, team *ent.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTeam", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTeam indicates an expected call of DeleteTeam.
func (mr *MockTeamsRepoMockRecorder) DeleteTeam(ctx, team interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTeam", reflect.TypeOf((*MockTeamsRepo)(nil).DeleteTeam), ctx, team)
}

// GetTeam mocks base method.
func (m *MockTeamsRepo) GetTeam(ctx context.Context, teamId, tenantId int64, getTree bool) (*ent.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamId, tenantId, getTree)
	ret0, _ := ret[0].(*ent.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockTeamsRepoMockRecorder) GetTeam(ctx, teamId, tenantId, getTree interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockTeamsRepo)(nil).GetTeam), ctx, teamId, tenantId, getTree)
}

// GetTeams mocks base method.
func (m *MockTeamsRepo) GetTeams(ctx context.Context, tenantId int64, teamIds []int64) ([]*ent.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeams", ctx, tenantId, teamIds)
	ret0, _ := ret[0].([]*ent.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeams indicates an expected call of GetTeams.
func (mr *MockTeamsRepoMockRecorder) GetTeams(ctx, tenantId, teamIds interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeams", reflect.TypeOf((*MockTeamsRepo)(nil).GetTeams), ctx, tenantId, teamIds)
}

// ListTeams mocks base method.
func (m *MockTeamsRepo) ListTeams(ctx context.Context, filter data.TeamsListFilter, paginate *utils_v1.PaginateRequest) ([]*ent.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTeams", ctx, filter, paginate)
	ret0, _ := ret[0].([]*ent.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTeams indicates an expected call of ListTeams.
func (mr *MockTeamsRepoMockRecorder) ListTeams(ctx, filter, paginate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTeams", reflect.TypeOf((*MockTeamsRepo)(nil).ListTeams), ctx, filter, paginate)
}

// UpdateTeam mocks base method.
func (m *MockTeamsRepo) UpdateTeam(ctx context.Context, team *ent.Team, dto data.TeamDto) (*ent.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTeam", ctx, team, dto)
	ret0, _ := ret[0].(*ent.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateTeam indicates an expected call of UpdateTeam.
func (mr *MockTeamsRepoMockRecorder) UpdateTeam(ctx, team, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTeam", reflect.TypeOf((*MockTeamsRepo)(nil).UpdateTeam), ctx, team, dto)
}
