// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/rbac/internal/biz"
	"gitlab.calendaria.team/services/rbac/internal/conf"
	"gitlab.calendaria.team/services/rbac/internal/data"
	"gitlab.calendaria.team/services/rbac/internal/server"
	"gitlab.calendaria.team/services/rbac/internal/service"
	"gitlab.calendaria.team/services/utils/v1/config"
	"gitlab.calendaria.team/services/utils/v1/jwt"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := jwt.NewJwtProcessor(configConfig)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, configConfig, logger)
	if err != nil {
		return nil, nil, err
	}
	assignedRolesRepo := data.NewAssignedRolesRepo(dataData)
	roleRepo := data.NewRoleRepo(dataData)
	teamsRepo := data.NewTeamsRepo(dataData)
	checkPermissionsUsecase, err := biz.NewCheckPermissionsUsecase(assignedRolesRepo, roleRepo, teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	serviceHelper := service.NewServiceHelper(jwtProcessor, checkPermissionsUsecase)
	rolesUsecase, err := biz.NewRolesUsecase(logger, roleRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionsUsecase, err := biz.NewPermissionsUsecase(logger, permissionRepo, roleRepo, assignedRolesRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	assignedRolesUsecase, err := biz.NewAssignedRolesUsecase(assignedRolesRepo, roleRepo, teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rolesService := service.NewRolesService(serviceHelper, rolesUsecase, permissionsUsecase, assignedRolesUsecase)
	permissionsService := service.NewPermissionsService(serviceHelper, permissionsUsecase)
	teamsUsecase, err := biz.NewTeamsUsecase(teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	teamsService := service.NewTeamsService(serviceHelper, teamsUsecase)
	assignsService := service.NewAssignsService(rolesUsecase, teamsUsecase, assignedRolesUsecase, serviceHelper)
	checkPermissionsService := service.NewCheckPermissionsService(checkPermissionsUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, jwtProcessor, rolesService, permissionsService, teamsService, assignsService, checkPermissionsService)
	httpServer := server.NewHTTPServer(bootstrap, jwtProcessor, rolesService, permissionsService, teamsService, assignsService, checkPermissionsService)
	app := newApp(logger, configConfig, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
