// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MemberRolesColumns holds the columns for the "member_roles" table.
	MemberRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "member_id", Type: field.TypeInt64},
		{Name: "role_id", Type: field.TypeInt64},
		{Name: "team_id", Type: field.TypeInt64},
	}
	// MemberRolesTable holds the schema information for the "member_roles" table.
	MemberRolesTable = &schema.Table{
		Name:       "member_roles",
		Columns:    MemberRolesColumns,
		PrimaryKey: []*schema.Column{MemberRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "member_roles_roles_role",
				Columns:    []*schema.Column{MemberRolesColumns[2]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "member_roles_roles_teams",
				Columns:    []*schema.Column{MemberRolesColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "memberrole_member_id_role_id_team_id",
				Unique:  true,
				Columns: []*schema.Column{MemberRolesColumns[1], MemberRolesColumns[2], MemberRolesColumns[3]},
			},
		},
	}
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Size: 32},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "app_id", Type: field.TypeString, Size: 10},
		{Name: "fields", Type: field.TypeJSON, Nullable: true},
		{Name: "role_permissions", Type: field.TypeInt64, Nullable: true},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "permissions_roles_permissions",
				Columns:    []*schema.Column{PermissionsColumns[5]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "name", Type: field.TypeString, Size: 32},
		{Name: "description", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "team_id", Type: field.TypeInt64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "permission_roles", Type: field.TypeString, Nullable: true},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "roles_permissions_roles",
				Columns:    []*schema.Column{RolesColumns[6]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "fields", Type: field.TypeJSON},
		{Name: "role_id", Type: field.TypeInt64},
		{Name: "permission_id", Type: field.TypeString},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_roles_role",
				Columns:    []*schema.Column{RolePermissionsColumns[2]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_permissions_permissions_permission",
				Columns:    []*schema.Column{RolePermissionsColumns[3]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{RolePermissionsColumns[2], RolePermissionsColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MemberRolesTable,
		PermissionsTable,
		RolesTable,
		RolePermissionsTable,
	}
)

func init() {
	MemberRolesTable.ForeignKeys[0].RefTable = RolesTable
	MemberRolesTable.ForeignKeys[1].RefTable = RolesTable
	PermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolesTable.ForeignKeys[0].RefTable = PermissionsTable
	RolePermissionsTable.ForeignKeys[0].RefTable = RolesTable
	RolePermissionsTable.ForeignKeys[1].RefTable = PermissionsTable
}
