// Code generated by ent, DO NOT EDIT.

package teamidentityrole

import (
	"rbac/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLTE(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldTenantID, v))
}

// TeamID applies equality check predicate on the "team_id" field. It's identical to TeamIDEQ.
func TeamID(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldTeamID, v))
}

// IdentityID applies equality check predicate on the "identity_id" field. It's identical to IdentityIDEQ.
func IdentityID(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldIdentityID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldRoleID, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLTE(FieldTenantID, v))
}

// TeamIDEQ applies the EQ predicate on the "team_id" field.
func TeamIDEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldTeamID, v))
}

// TeamIDNEQ applies the NEQ predicate on the "team_id" field.
func TeamIDNEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNEQ(FieldTeamID, v))
}

// TeamIDIn applies the In predicate on the "team_id" field.
func TeamIDIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldIn(FieldTeamID, vs...))
}

// TeamIDNotIn applies the NotIn predicate on the "team_id" field.
func TeamIDNotIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNotIn(FieldTeamID, vs...))
}

// IdentityIDEQ applies the EQ predicate on the "identity_id" field.
func IdentityIDEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldIdentityID, v))
}

// IdentityIDNEQ applies the NEQ predicate on the "identity_id" field.
func IdentityIDNEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNEQ(FieldIdentityID, v))
}

// IdentityIDIn applies the In predicate on the "identity_id" field.
func IdentityIDIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldIn(FieldIdentityID, vs...))
}

// IdentityIDNotIn applies the NotIn predicate on the "identity_id" field.
func IdentityIDNotIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNotIn(FieldIdentityID, vs...))
}

// IdentityIDGT applies the GT predicate on the "identity_id" field.
func IdentityIDGT(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGT(FieldIdentityID, v))
}

// IdentityIDGTE applies the GTE predicate on the "identity_id" field.
func IdentityIDGTE(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldGTE(FieldIdentityID, v))
}

// IdentityIDLT applies the LT predicate on the "identity_id" field.
func IdentityIDLT(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLT(FieldIdentityID, v))
}

// IdentityIDLTE applies the LTE predicate on the "identity_id" field.
func IdentityIDLTE(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldLTE(FieldIdentityID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...int64) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(sql.FieldNotIn(FieldRoleID, vs...))
}

// HasRole applies the HasEdge predicate on the "role" edge.
func HasRole() predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, RoleTable, RoleColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRoleWith applies the HasEdge predicate on the "role" edge with a given conditions (other predicates).
func HasRoleWith(preds ...predicate.Role) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		step := newRoleStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTeam applies the HasEdge predicate on the "team" edge.
func HasTeam() predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TeamTable, TeamColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTeamWith applies the HasEdge predicate on the "team" edge with a given conditions (other predicates).
func HasTeamWith(preds ...predicate.Team) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		step := newTeamStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TeamIdentityRole) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TeamIdentityRole) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TeamIdentityRole) predicate.TeamIdentityRole {
	return predicate.TeamIdentityRole(func(s *sql.Selector) {
		p(s.Not())
	})
}
