// Code generated by ent, DO NOT EDIT.

package ent

import (
	"dummy/ent/dummy"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/entql"
	"entgo.io/ent/schema/field"
)

// schemaGraph holds a representation of ent/schema at runtime.
var schemaGraph = func() *sqlgraph.Schema {
	graph := &sqlgraph.Schema{Nodes: make([]*sqlgraph.Node, 1)}
	graph.Nodes[0] = &sqlgraph.Node{
		NodeSpec: sqlgraph.NodeSpec{
			Table:   dummy.Table,
			Columns: dummy.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt64,
				Column: dummy.FieldID,
			},
		},
		Type: "Dummy",
		Fields: map[string]*sqlgraph.FieldSpec{
			dummy.FieldUserID:    {Type: field.TypeInt64, Column: dummy.FieldUserID},
			dummy.FieldName:      {Type: field.TypeString, Column: dummy.FieldName},
			dummy.FieldCreatedAt: {Type: field.TypeTime, Column: dummy.FieldCreatedAt},
			dummy.FieldUpdatedAt: {Type: field.TypeTime, Column: dummy.FieldUpdatedAt},
		},
	}
	return graph
}()

// predicateAdder wraps the addPredicate method.
// All update, update-one and query builders implement this interface.
type predicateAdder interface {
	addPredicate(func(s *sql.Selector))
}

// addPredicate implements the predicateAdder interface.
func (dq *DummyQuery) addPredicate(pred func(s *sql.Selector)) {
	dq.predicates = append(dq.predicates, pred)
}

// Filter returns a Filter implementation to apply filters on the DummyQuery builder.
func (dq *DummyQuery) Filter() *DummyFilter {
	return &DummyFilter{config: dq.config, predicateAdder: dq}
}

// addPredicate implements the predicateAdder interface.
func (m *DummyMutation) addPredicate(pred func(s *sql.Selector)) {
	m.predicates = append(m.predicates, pred)
}

// Filter returns an entql.Where implementation to apply filters on the DummyMutation builder.
func (m *DummyMutation) Filter() *DummyFilter {
	return &DummyFilter{config: m.config, predicateAdder: m}
}

// DummyFilter provides a generic filtering capability at runtime for DummyQuery.
type DummyFilter struct {
	predicateAdder
	config
}

// Where applies the entql predicate on the query filter.
func (f *DummyFilter) Where(p entql.P) {
	f.addPredicate(func(s *sql.Selector) {
		if err := schemaGraph.EvalP(schemaGraph.Nodes[0].Type, p, s); err != nil {
			s.AddError(err)
		}
	})
}

// WhereID applies the entql int64 predicate on the id field.
func (f *DummyFilter) WhereID(p entql.Int64P) {
	f.Where(p.Field(dummy.FieldID))
}

// WhereUserID applies the entql int64 predicate on the user_id field.
func (f *DummyFilter) WhereUserID(p entql.Int64P) {
	f.Where(p.Field(dummy.FieldUserID))
}

// WhereName applies the entql string predicate on the name field.
func (f *DummyFilter) WhereName(p entql.StringP) {
	f.Where(p.Field(dummy.FieldName))
}

// WhereCreatedAt applies the entql time.Time predicate on the created_at field.
func (f *DummyFilter) WhereCreatedAt(p entql.TimeP) {
	f.Where(p.Field(dummy.FieldCreatedAt))
}

// WhereUpdatedAt applies the entql time.Time predicate on the updated_at field.
func (f *DummyFilter) WhereUpdatedAt(p entql.TimeP) {
	f.Where(p.Field(dummy.FieldUpdatedAt))
}
