// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"media/ent/media"
	"media/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MediaUpdate is the builder for updating Media entities.
type MediaUpdate struct {
	config
	hooks    []Hook
	mutation *MediaMutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (mu *MediaUpdate) Where(ps ...predicate.Media) *MediaUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetUserID sets the "user_id" field.
func (mu *MediaUpdate) SetUserID(i int64) *MediaUpdate {
	mu.mutation.ResetUserID()
	mu.mutation.SetUserID(i)
	return mu
}

// AddUserID adds i to the "user_id" field.
func (mu *MediaUpdate) AddUserID(i int64) *MediaUpdate {
	mu.mutation.AddUserID(i)
	return mu
}

// SetLocation sets the "location" field.
func (mu *MediaUpdate) SetLocation(s string) *MediaUpdate {
	mu.mutation.SetLocation(s)
	return mu
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableLocation(s *string) *MediaUpdate {
	if s != nil {
		mu.SetLocation(*s)
	}
	return mu
}

// ClearLocation clears the value of the "location" field.
func (mu *MediaUpdate) ClearLocation() *MediaUpdate {
	mu.mutation.ClearLocation()
	return mu
}

// SetCreatedAt sets the "created_at" field.
func (mu *MediaUpdate) SetCreatedAt(t time.Time) *MediaUpdate {
	mu.mutation.SetCreatedAt(t)
	return mu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableCreatedAt(t *time.Time) *MediaUpdate {
	if t != nil {
		mu.SetCreatedAt(*t)
	}
	return mu
}

// SetUploadedAt sets the "uploaded_at" field.
func (mu *MediaUpdate) SetUploadedAt(t time.Time) *MediaUpdate {
	mu.mutation.SetUploadedAt(t)
	return mu
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (mu *MediaUpdate) SetNillableUploadedAt(t *time.Time) *MediaUpdate {
	if t != nil {
		mu.SetUploadedAt(*t)
	}
	return mu
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (mu *MediaUpdate) ClearUploadedAt() *MediaUpdate {
	mu.mutation.ClearUploadedAt()
	return mu
}

// Mutation returns the MediaMutation object of the builder.
func (mu *MediaUpdate) Mutation() *MediaMutation {
	return mu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MediaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MediaUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MediaUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MediaUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MediaUpdate) check() error {
	if v, ok := mu.mutation.UserID(); ok {
		if err := media.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Media.user_id": %w`, err)}
		}
	}
	return nil
}

func (mu *MediaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt64))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.UserID(); ok {
		_spec.SetField(media.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedUserID(); ok {
		_spec.AddField(media.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.Location(); ok {
		_spec.SetField(media.FieldLocation, field.TypeString, value)
	}
	if mu.mutation.LocationCleared() {
		_spec.ClearField(media.FieldLocation, field.TypeString)
	}
	if value, ok := mu.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.UploadedAt(); ok {
		_spec.SetField(media.FieldUploadedAt, field.TypeTime, value)
	}
	if mu.mutation.UploadedAtCleared() {
		_spec.ClearField(media.FieldUploadedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MediaUpdateOne is the builder for updating a single Media entity.
type MediaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MediaMutation
}

// SetUserID sets the "user_id" field.
func (muo *MediaUpdateOne) SetUserID(i int64) *MediaUpdateOne {
	muo.mutation.ResetUserID()
	muo.mutation.SetUserID(i)
	return muo
}

// AddUserID adds i to the "user_id" field.
func (muo *MediaUpdateOne) AddUserID(i int64) *MediaUpdateOne {
	muo.mutation.AddUserID(i)
	return muo
}

// SetLocation sets the "location" field.
func (muo *MediaUpdateOne) SetLocation(s string) *MediaUpdateOne {
	muo.mutation.SetLocation(s)
	return muo
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableLocation(s *string) *MediaUpdateOne {
	if s != nil {
		muo.SetLocation(*s)
	}
	return muo
}

// ClearLocation clears the value of the "location" field.
func (muo *MediaUpdateOne) ClearLocation() *MediaUpdateOne {
	muo.mutation.ClearLocation()
	return muo
}

// SetCreatedAt sets the "created_at" field.
func (muo *MediaUpdateOne) SetCreatedAt(t time.Time) *MediaUpdateOne {
	muo.mutation.SetCreatedAt(t)
	return muo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableCreatedAt(t *time.Time) *MediaUpdateOne {
	if t != nil {
		muo.SetCreatedAt(*t)
	}
	return muo
}

// SetUploadedAt sets the "uploaded_at" field.
func (muo *MediaUpdateOne) SetUploadedAt(t time.Time) *MediaUpdateOne {
	muo.mutation.SetUploadedAt(t)
	return muo
}

// SetNillableUploadedAt sets the "uploaded_at" field if the given value is not nil.
func (muo *MediaUpdateOne) SetNillableUploadedAt(t *time.Time) *MediaUpdateOne {
	if t != nil {
		muo.SetUploadedAt(*t)
	}
	return muo
}

// ClearUploadedAt clears the value of the "uploaded_at" field.
func (muo *MediaUpdateOne) ClearUploadedAt() *MediaUpdateOne {
	muo.mutation.ClearUploadedAt()
	return muo
}

// Mutation returns the MediaMutation object of the builder.
func (muo *MediaUpdateOne) Mutation() *MediaMutation {
	return muo.mutation
}

// Where appends a list predicates to the MediaUpdate builder.
func (muo *MediaUpdateOne) Where(ps ...predicate.Media) *MediaUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MediaUpdateOne) Select(field string, fields ...string) *MediaUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Media entity.
func (muo *MediaUpdateOne) Save(ctx context.Context) (*Media, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MediaUpdateOne) SaveX(ctx context.Context) *Media {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MediaUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MediaUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MediaUpdateOne) check() error {
	if v, ok := muo.mutation.UserID(); ok {
		if err := media.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Media.user_id": %w`, err)}
		}
	}
	return nil
}

func (muo *MediaUpdateOne) sqlSave(ctx context.Context) (_node *Media, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(media.Table, media.Columns, sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt64))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Media.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, media.FieldID)
		for _, f := range fields {
			if !media.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != media.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.UserID(); ok {
		_spec.SetField(media.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedUserID(); ok {
		_spec.AddField(media.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.Location(); ok {
		_spec.SetField(media.FieldLocation, field.TypeString, value)
	}
	if muo.mutation.LocationCleared() {
		_spec.ClearField(media.FieldLocation, field.TypeString)
	}
	if value, ok := muo.mutation.CreatedAt(); ok {
		_spec.SetField(media.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.UploadedAt(); ok {
		_spec.SetField(media.FieldUploadedAt, field.TypeTime, value)
	}
	if muo.mutation.UploadedAtCleared() {
		_spec.ClearField(media.FieldUploadedAt, field.TypeTime)
	}
	_node = &Media{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{media.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
