// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rbac/ent/memberrole"
	"rbac/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberRoleUpdate is the builder for updating MemberRole entities.
type MemberRoleUpdate struct {
	config
	hooks     []Hook
	mutation  *MemberRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the MemberRoleUpdate builder.
func (mru *MemberRoleUpdate) Where(ps ...predicate.MemberRole) *MemberRoleUpdate {
	mru.mutation.Where(ps...)
	return mru
}

// Mutation returns the MemberRoleMutation object of the builder.
func (mru *MemberRoleUpdate) Mutation() *MemberRoleMutation {
	return mru.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mru *MemberRoleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mru.sqlSave, mru.mutation, mru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mru *MemberRoleUpdate) SaveX(ctx context.Context) int {
	affected, err := mru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mru *MemberRoleUpdate) Exec(ctx context.Context) error {
	_, err := mru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mru *MemberRoleUpdate) ExecX(ctx context.Context) {
	if err := mru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mru *MemberRoleUpdate) check() error {
	if _, ok := mru.mutation.RoleID(); mru.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "MemberRole.role"`)
	}
	if _, ok := mru.mutation.TeamsID(); mru.mutation.TeamsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "MemberRole.teams"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mru *MemberRoleUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberRoleUpdate {
	mru.modifiers = append(mru.modifiers, modifiers...)
	return mru
}

func (mru *MemberRoleUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberrole.Table, memberrole.Columns, sqlgraph.NewFieldSpec(memberrole.FieldID, field.TypeInt64))
	if ps := mru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.AddModifiers(mru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, mru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mru.mutation.done = true
	return n, nil
}

// MemberRoleUpdateOne is the builder for updating a single MemberRole entity.
type MemberRoleUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *MemberRoleMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Mutation returns the MemberRoleMutation object of the builder.
func (mruo *MemberRoleUpdateOne) Mutation() *MemberRoleMutation {
	return mruo.mutation
}

// Where appends a list predicates to the MemberRoleUpdate builder.
func (mruo *MemberRoleUpdateOne) Where(ps ...predicate.MemberRole) *MemberRoleUpdateOne {
	mruo.mutation.Where(ps...)
	return mruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (mruo *MemberRoleUpdateOne) Select(field string, fields ...string) *MemberRoleUpdateOne {
	mruo.fields = append([]string{field}, fields...)
	return mruo
}

// Save executes the query and returns the updated MemberRole entity.
func (mruo *MemberRoleUpdateOne) Save(ctx context.Context) (*MemberRole, error) {
	return withHooks(ctx, mruo.sqlSave, mruo.mutation, mruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mruo *MemberRoleUpdateOne) SaveX(ctx context.Context) *MemberRole {
	node, err := mruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (mruo *MemberRoleUpdateOne) Exec(ctx context.Context) error {
	_, err := mruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mruo *MemberRoleUpdateOne) ExecX(ctx context.Context) {
	if err := mruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mruo *MemberRoleUpdateOne) check() error {
	if _, ok := mruo.mutation.RoleID(); mruo.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "MemberRole.role"`)
	}
	if _, ok := mruo.mutation.TeamsID(); mruo.mutation.TeamsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "MemberRole.teams"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (mruo *MemberRoleUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *MemberRoleUpdateOne {
	mruo.modifiers = append(mruo.modifiers, modifiers...)
	return mruo
}

func (mruo *MemberRoleUpdateOne) sqlSave(ctx context.Context) (_node *MemberRole, err error) {
	if err := mruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memberrole.Table, memberrole.Columns, sqlgraph.NewFieldSpec(memberrole.FieldID, field.TypeInt64))
	id, ok := mruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "MemberRole.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := mruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberrole.FieldID)
		for _, f := range fields {
			if !memberrole.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memberrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := mruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_spec.AddModifiers(mruo.modifiers...)
	_node = &MemberRole{config: mruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, mruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memberrole.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	mruo.mutation.done = true
	return _node, nil
}
