// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"rbac/ent/memberrole"
	"rbac/ent/predicate"
	"rbac/ent/role"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MemberRoleQuery is the builder for querying MemberRole entities.
type MemberRoleQuery struct {
	config
	ctx        *QueryContext
	order      []memberrole.OrderOption
	inters     []Interceptor
	predicates []predicate.MemberRole
	withRole   *RoleQuery
	withTeams  *RoleQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MemberRoleQuery builder.
func (mrq *MemberRoleQuery) Where(ps ...predicate.MemberRole) *MemberRoleQuery {
	mrq.predicates = append(mrq.predicates, ps...)
	return mrq
}

// Limit the number of records to be returned by this query.
func (mrq *MemberRoleQuery) Limit(limit int) *MemberRoleQuery {
	mrq.ctx.Limit = &limit
	return mrq
}

// Offset to start from.
func (mrq *MemberRoleQuery) Offset(offset int) *MemberRoleQuery {
	mrq.ctx.Offset = &offset
	return mrq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mrq *MemberRoleQuery) Unique(unique bool) *MemberRoleQuery {
	mrq.ctx.Unique = &unique
	return mrq
}

// Order specifies how the records should be ordered.
func (mrq *MemberRoleQuery) Order(o ...memberrole.OrderOption) *MemberRoleQuery {
	mrq.order = append(mrq.order, o...)
	return mrq
}

// QueryRole chains the current query on the "role" edge.
func (mrq *MemberRoleQuery) QueryRole() *RoleQuery {
	query := (&RoleClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memberrole.Table, memberrole.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, memberrole.RoleTable, memberrole.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeams chains the current query on the "teams" edge.
func (mrq *MemberRoleQuery) QueryTeams() *RoleQuery {
	query := (&RoleClient{config: mrq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := mrq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := mrq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(memberrole.Table, memberrole.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, memberrole.TeamsTable, memberrole.TeamsColumn),
		)
		fromU = sqlgraph.SetNeighbors(mrq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first MemberRole entity from the query.
// Returns a *NotFoundError when no MemberRole was found.
func (mrq *MemberRoleQuery) First(ctx context.Context) (*MemberRole, error) {
	nodes, err := mrq.Limit(1).All(setContextOp(ctx, mrq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{memberrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mrq *MemberRoleQuery) FirstX(ctx context.Context) *MemberRole {
	node, err := mrq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MemberRole ID from the query.
// Returns a *NotFoundError when no MemberRole ID was found.
func (mrq *MemberRoleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mrq.Limit(1).IDs(setContextOp(ctx, mrq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{memberrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mrq *MemberRoleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := mrq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MemberRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MemberRole entity is found.
// Returns a *NotFoundError when no MemberRole entities are found.
func (mrq *MemberRoleQuery) Only(ctx context.Context) (*MemberRole, error) {
	nodes, err := mrq.Limit(2).All(setContextOp(ctx, mrq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{memberrole.Label}
	default:
		return nil, &NotSingularError{memberrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mrq *MemberRoleQuery) OnlyX(ctx context.Context) *MemberRole {
	node, err := mrq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MemberRole ID in the query.
// Returns a *NotSingularError when more than one MemberRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (mrq *MemberRoleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = mrq.Limit(2).IDs(setContextOp(ctx, mrq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{memberrole.Label}
	default:
		err = &NotSingularError{memberrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mrq *MemberRoleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := mrq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MemberRoles.
func (mrq *MemberRoleQuery) All(ctx context.Context) ([]*MemberRole, error) {
	ctx = setContextOp(ctx, mrq.ctx, "All")
	if err := mrq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MemberRole, *MemberRoleQuery]()
	return withInterceptors[[]*MemberRole](ctx, mrq, qr, mrq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mrq *MemberRoleQuery) AllX(ctx context.Context) []*MemberRole {
	nodes, err := mrq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MemberRole IDs.
func (mrq *MemberRoleQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if mrq.ctx.Unique == nil && mrq.path != nil {
		mrq.Unique(true)
	}
	ctx = setContextOp(ctx, mrq.ctx, "IDs")
	if err = mrq.Select(memberrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mrq *MemberRoleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := mrq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mrq *MemberRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Count")
	if err := mrq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mrq, querierCount[*MemberRoleQuery](), mrq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mrq *MemberRoleQuery) CountX(ctx context.Context) int {
	count, err := mrq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mrq *MemberRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mrq.ctx, "Exist")
	switch _, err := mrq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mrq *MemberRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := mrq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MemberRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mrq *MemberRoleQuery) Clone() *MemberRoleQuery {
	if mrq == nil {
		return nil
	}
	return &MemberRoleQuery{
		config:     mrq.config,
		ctx:        mrq.ctx.Clone(),
		order:      append([]memberrole.OrderOption{}, mrq.order...),
		inters:     append([]Interceptor{}, mrq.inters...),
		predicates: append([]predicate.MemberRole{}, mrq.predicates...),
		withRole:   mrq.withRole.Clone(),
		withTeams:  mrq.withTeams.Clone(),
		// clone intermediate query.
		sql:  mrq.sql.Clone(),
		path: mrq.path,
	}
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MemberRoleQuery) WithRole(opts ...func(*RoleQuery)) *MemberRoleQuery {
	query := (&RoleClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withRole = query
	return mrq
}

// WithTeams tells the query-builder to eager-load the nodes that are connected to
// the "teams" edge. The optional arguments are used to configure the query builder of the edge.
func (mrq *MemberRoleQuery) WithTeams(opts ...func(*RoleQuery)) *MemberRoleQuery {
	query := (&RoleClient{config: mrq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	mrq.withTeams = query
	return mrq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"member_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MemberRole.Query().
//		GroupBy(memberrole.FieldMemberID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mrq *MemberRoleQuery) GroupBy(field string, fields ...string) *MemberRoleGroupBy {
	mrq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MemberRoleGroupBy{build: mrq}
	grbuild.flds = &mrq.ctx.Fields
	grbuild.label = memberrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MemberID int64 `json:"member_id,omitempty"`
//	}
//
//	client.MemberRole.Query().
//		Select(memberrole.FieldMemberID).
//		Scan(ctx, &v)
func (mrq *MemberRoleQuery) Select(fields ...string) *MemberRoleSelect {
	mrq.ctx.Fields = append(mrq.ctx.Fields, fields...)
	sbuild := &MemberRoleSelect{MemberRoleQuery: mrq}
	sbuild.label = memberrole.Label
	sbuild.flds, sbuild.scan = &mrq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MemberRoleSelect configured with the given aggregations.
func (mrq *MemberRoleQuery) Aggregate(fns ...AggregateFunc) *MemberRoleSelect {
	return mrq.Select().Aggregate(fns...)
}

func (mrq *MemberRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mrq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mrq); err != nil {
				return err
			}
		}
	}
	for _, f := range mrq.ctx.Fields {
		if !memberrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mrq.path != nil {
		prev, err := mrq.path(ctx)
		if err != nil {
			return err
		}
		mrq.sql = prev
	}
	return nil
}

func (mrq *MemberRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MemberRole, error) {
	var (
		nodes       = []*MemberRole{}
		_spec       = mrq.querySpec()
		loadedTypes = [2]bool{
			mrq.withRole != nil,
			mrq.withTeams != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MemberRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MemberRole{config: mrq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(mrq.modifiers) > 0 {
		_spec.Modifiers = mrq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mrq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := mrq.withRole; query != nil {
		if err := mrq.loadRole(ctx, query, nodes, nil,
			func(n *MemberRole, e *Role) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	if query := mrq.withTeams; query != nil {
		if err := mrq.loadTeams(ctx, query, nodes, nil,
			func(n *MemberRole, e *Role) { n.Edges.Teams = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (mrq *MemberRoleQuery) loadRole(ctx context.Context, query *RoleQuery, nodes []*MemberRole, init func(*MemberRole), assign func(*MemberRole, *Role)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MemberRole)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (mrq *MemberRoleQuery) loadTeams(ctx context.Context, query *RoleQuery, nodes []*MemberRole, init func(*MemberRole), assign func(*MemberRole, *Role)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*MemberRole)
	for i := range nodes {
		fk := nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (mrq *MemberRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mrq.querySpec()
	if len(mrq.modifiers) > 0 {
		_spec.Modifiers = mrq.modifiers
	}
	_spec.Node.Columns = mrq.ctx.Fields
	if len(mrq.ctx.Fields) > 0 {
		_spec.Unique = mrq.ctx.Unique != nil && *mrq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mrq.driver, _spec)
}

func (mrq *MemberRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(memberrole.Table, memberrole.Columns, sqlgraph.NewFieldSpec(memberrole.FieldID, field.TypeInt64))
	_spec.From = mrq.sql
	if unique := mrq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mrq.path != nil {
		_spec.Unique = true
	}
	if fields := mrq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memberrole.FieldID)
		for i := range fields {
			if fields[i] != memberrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if mrq.withRole != nil {
			_spec.Node.AddColumnOnce(memberrole.FieldRoleID)
		}
		if mrq.withTeams != nil {
			_spec.Node.AddColumnOnce(memberrole.FieldTeamID)
		}
	}
	if ps := mrq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mrq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mrq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mrq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mrq *MemberRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mrq.driver.Dialect())
	t1 := builder.Table(memberrole.Table)
	columns := mrq.ctx.Fields
	if len(columns) == 0 {
		columns = memberrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mrq.sql != nil {
		selector = mrq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mrq.ctx.Unique != nil && *mrq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range mrq.modifiers {
		m(selector)
	}
	for _, p := range mrq.predicates {
		p(selector)
	}
	for _, p := range mrq.order {
		p(selector)
	}
	if offset := mrq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mrq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mrq *MemberRoleQuery) Modify(modifiers ...func(s *sql.Selector)) *MemberRoleSelect {
	mrq.modifiers = append(mrq.modifiers, modifiers...)
	return mrq.Select()
}

// MemberRoleGroupBy is the group-by builder for MemberRole entities.
type MemberRoleGroupBy struct {
	selector
	build *MemberRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mrgb *MemberRoleGroupBy) Aggregate(fns ...AggregateFunc) *MemberRoleGroupBy {
	mrgb.fns = append(mrgb.fns, fns...)
	return mrgb
}

// Scan applies the selector query and scans the result into the given value.
func (mrgb *MemberRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrgb.build.ctx, "GroupBy")
	if err := mrgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberRoleQuery, *MemberRoleGroupBy](ctx, mrgb.build, mrgb, mrgb.build.inters, v)
}

func (mrgb *MemberRoleGroupBy) sqlScan(ctx context.Context, root *MemberRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mrgb.fns))
	for _, fn := range mrgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mrgb.flds)+len(mrgb.fns))
		for _, f := range *mrgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mrgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MemberRoleSelect is the builder for selecting fields of MemberRole entities.
type MemberRoleSelect struct {
	*MemberRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mrs *MemberRoleSelect) Aggregate(fns ...AggregateFunc) *MemberRoleSelect {
	mrs.fns = append(mrs.fns, fns...)
	return mrs
}

// Scan applies the selector query and scans the result into the given value.
func (mrs *MemberRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mrs.ctx, "Select")
	if err := mrs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MemberRoleQuery, *MemberRoleSelect](ctx, mrs.MemberRoleQuery, mrs, mrs.inters, v)
}

func (mrs *MemberRoleSelect) sqlScan(ctx context.Context, root *MemberRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mrs.fns))
	for _, fn := range mrs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mrs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mrs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (mrs *MemberRoleSelect) Modify(modifiers ...func(s *sql.Selector)) *MemberRoleSelect {
	mrs.modifiers = append(mrs.modifiers, modifiers...)
	return mrs
}
