// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/rbac/ent/permission"
	"gitlab.calendaria.team/services/rbac/ent/permissiongroup"
	"gitlab.calendaria.team/services/rbac/ent/predicate"
)

// PermissionGroupUpdate is the builder for updating PermissionGroup entities.
type PermissionGroupUpdate struct {
	config
	hooks     []Hook
	mutation  *PermissionGroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the PermissionGroupUpdate builder.
func (pgu *PermissionGroupUpdate) Where(ps ...predicate.PermissionGroup) *PermissionGroupUpdate {
	pgu.mutation.Where(ps...)
	return pgu
}

// SetName sets the "name" field.
func (pgu *PermissionGroupUpdate) SetName(s string) *PermissionGroupUpdate {
	pgu.mutation.SetName(s)
	return pgu
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pgu *PermissionGroupUpdate) SetNillableName(s *string) *PermissionGroupUpdate {
	if s != nil {
		pgu.SetName(*s)
	}
	return pgu
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (pgu *PermissionGroupUpdate) AddPermissionIDs(ids ...string) *PermissionGroupUpdate {
	pgu.mutation.AddPermissionIDs(ids...)
	return pgu
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (pgu *PermissionGroupUpdate) AddPermissions(p ...*Permission) *PermissionGroupUpdate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pgu.AddPermissionIDs(ids...)
}

// Mutation returns the PermissionGroupMutation object of the builder.
func (pgu *PermissionGroupUpdate) Mutation() *PermissionGroupMutation {
	return pgu.mutation
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (pgu *PermissionGroupUpdate) ClearPermissions() *PermissionGroupUpdate {
	pgu.mutation.ClearPermissions()
	return pgu
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (pgu *PermissionGroupUpdate) RemovePermissionIDs(ids ...string) *PermissionGroupUpdate {
	pgu.mutation.RemovePermissionIDs(ids...)
	return pgu
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (pgu *PermissionGroupUpdate) RemovePermissions(p ...*Permission) *PermissionGroupUpdate {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pgu.RemovePermissionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (pgu *PermissionGroupUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, pgu.sqlSave, pgu.mutation, pgu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pgu *PermissionGroupUpdate) SaveX(ctx context.Context) int {
	affected, err := pgu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (pgu *PermissionGroupUpdate) Exec(ctx context.Context) error {
	_, err := pgu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pgu *PermissionGroupUpdate) ExecX(ctx context.Context) {
	if err := pgu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pgu *PermissionGroupUpdate) check() error {
	if v, ok := pgu.mutation.Name(); ok {
		if err := permissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pgu *PermissionGroupUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionGroupUpdate {
	pgu.modifiers = append(pgu.modifiers, modifiers...)
	return pgu
}

func (pgu *PermissionGroupUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := pgu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissiongroup.Table, permissiongroup.Columns, sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeString))
	if ps := pgu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pgu.mutation.Name(); ok {
		_spec.SetField(permissiongroup.FieldName, field.TypeString, value)
	}
	if pgu.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pgu.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !pgu.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pgu.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pgu.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, pgu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	pgu.mutation.done = true
	return n, nil
}

// PermissionGroupUpdateOne is the builder for updating a single PermissionGroup entity.
type PermissionGroupUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *PermissionGroupMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetName sets the "name" field.
func (pguo *PermissionGroupUpdateOne) SetName(s string) *PermissionGroupUpdateOne {
	pguo.mutation.SetName(s)
	return pguo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (pguo *PermissionGroupUpdateOne) SetNillableName(s *string) *PermissionGroupUpdateOne {
	if s != nil {
		pguo.SetName(*s)
	}
	return pguo
}

// AddPermissionIDs adds the "permissions" edge to the Permission entity by IDs.
func (pguo *PermissionGroupUpdateOne) AddPermissionIDs(ids ...string) *PermissionGroupUpdateOne {
	pguo.mutation.AddPermissionIDs(ids...)
	return pguo
}

// AddPermissions adds the "permissions" edges to the Permission entity.
func (pguo *PermissionGroupUpdateOne) AddPermissions(p ...*Permission) *PermissionGroupUpdateOne {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pguo.AddPermissionIDs(ids...)
}

// Mutation returns the PermissionGroupMutation object of the builder.
func (pguo *PermissionGroupUpdateOne) Mutation() *PermissionGroupMutation {
	return pguo.mutation
}

// ClearPermissions clears all "permissions" edges to the Permission entity.
func (pguo *PermissionGroupUpdateOne) ClearPermissions() *PermissionGroupUpdateOne {
	pguo.mutation.ClearPermissions()
	return pguo
}

// RemovePermissionIDs removes the "permissions" edge to Permission entities by IDs.
func (pguo *PermissionGroupUpdateOne) RemovePermissionIDs(ids ...string) *PermissionGroupUpdateOne {
	pguo.mutation.RemovePermissionIDs(ids...)
	return pguo
}

// RemovePermissions removes "permissions" edges to Permission entities.
func (pguo *PermissionGroupUpdateOne) RemovePermissions(p ...*Permission) *PermissionGroupUpdateOne {
	ids := make([]string, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return pguo.RemovePermissionIDs(ids...)
}

// Where appends a list predicates to the PermissionGroupUpdate builder.
func (pguo *PermissionGroupUpdateOne) Where(ps ...predicate.PermissionGroup) *PermissionGroupUpdateOne {
	pguo.mutation.Where(ps...)
	return pguo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pguo *PermissionGroupUpdateOne) Select(field string, fields ...string) *PermissionGroupUpdateOne {
	pguo.fields = append([]string{field}, fields...)
	return pguo
}

// Save executes the query and returns the updated PermissionGroup entity.
func (pguo *PermissionGroupUpdateOne) Save(ctx context.Context) (*PermissionGroup, error) {
	return withHooks(ctx, pguo.sqlSave, pguo.mutation, pguo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (pguo *PermissionGroupUpdateOne) SaveX(ctx context.Context) *PermissionGroup {
	node, err := pguo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pguo *PermissionGroupUpdateOne) Exec(ctx context.Context) error {
	_, err := pguo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pguo *PermissionGroupUpdateOne) ExecX(ctx context.Context) {
	if err := pguo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pguo *PermissionGroupUpdateOne) check() error {
	if v, ok := pguo.mutation.Name(); ok {
		if err := permissiongroup.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "PermissionGroup.name": %w`, err)}
		}
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (pguo *PermissionGroupUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *PermissionGroupUpdateOne {
	pguo.modifiers = append(pguo.modifiers, modifiers...)
	return pguo
}

func (pguo *PermissionGroupUpdateOne) sqlSave(ctx context.Context) (_node *PermissionGroup, err error) {
	if err := pguo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(permissiongroup.Table, permissiongroup.Columns, sqlgraph.NewFieldSpec(permissiongroup.FieldID, field.TypeString))
	id, ok := pguo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PermissionGroup.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pguo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, permissiongroup.FieldID)
		for _, f := range fields {
			if !permissiongroup.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != permissiongroup.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pguo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pguo.mutation.Name(); ok {
		_spec.SetField(permissiongroup.FieldName, field.TypeString, value)
	}
	if pguo.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pguo.mutation.RemovedPermissionsIDs(); len(nodes) > 0 && !pguo.mutation.PermissionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pguo.mutation.PermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permissiongroup.PermissionsTable,
			Columns: []string{permissiongroup.PermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permission.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(pguo.modifiers...)
	_node = &PermissionGroup{config: pguo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pguo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{permissiongroup.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	pguo.mutation.done = true
	return _node, nil
}
