// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/rbac/ent/resourceaccess"
	"gitlab.calendaria.team/services/rbac/ent/resourcetype"
	"gitlab.calendaria.team/services/rbac/ent/role"
)

// ResourceAccessCreate is the builder for creating a ResourceAccess entity.
type ResourceAccessCreate struct {
	config
	mutation *ResourceAccessMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (rac *ResourceAccessCreate) SetTenantID(i int64) *ResourceAccessCreate {
	rac.mutation.SetTenantID(i)
	return rac
}

// SetResourceType sets the "resource_type" field.
func (rac *ResourceAccessCreate) SetResourceType(s string) *ResourceAccessCreate {
	rac.mutation.SetResourceType(s)
	return rac
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (rac *ResourceAccessCreate) SetNillableResourceType(s *string) *ResourceAccessCreate {
	if s != nil {
		rac.SetResourceType(*s)
	}
	return rac
}

// SetResourceID sets the "resource_id" field.
func (rac *ResourceAccessCreate) SetResourceID(i int64) *ResourceAccessCreate {
	rac.mutation.SetResourceID(i)
	return rac
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (rac *ResourceAccessCreate) SetNillableResourceID(i *int64) *ResourceAccessCreate {
	if i != nil {
		rac.SetResourceID(*i)
	}
	return rac
}

// SetIdentityID sets the "identity_id" field.
func (rac *ResourceAccessCreate) SetIdentityID(s string) *ResourceAccessCreate {
	rac.mutation.SetIdentityID(s)
	return rac
}

// SetNillableIdentityID sets the "identity_id" field if the given value is not nil.
func (rac *ResourceAccessCreate) SetNillableIdentityID(s *string) *ResourceAccessCreate {
	if s != nil {
		rac.SetIdentityID(*s)
	}
	return rac
}

// SetRoleID sets the "role_id" field.
func (rac *ResourceAccessCreate) SetRoleID(i int64) *ResourceAccessCreate {
	rac.mutation.SetRoleID(i)
	return rac
}

// SetRole sets the "role" edge to the Role entity.
func (rac *ResourceAccessCreate) SetRole(r *Role) *ResourceAccessCreate {
	return rac.SetRoleID(r.ID)
}

// SetTypeID sets the "type" edge to the ResourceType entity by ID.
func (rac *ResourceAccessCreate) SetTypeID(id string) *ResourceAccessCreate {
	rac.mutation.SetTypeID(id)
	return rac
}

// SetNillableTypeID sets the "type" edge to the ResourceType entity by ID if the given value is not nil.
func (rac *ResourceAccessCreate) SetNillableTypeID(id *string) *ResourceAccessCreate {
	if id != nil {
		rac = rac.SetTypeID(*id)
	}
	return rac
}

// SetType sets the "type" edge to the ResourceType entity.
func (rac *ResourceAccessCreate) SetType(r *ResourceType) *ResourceAccessCreate {
	return rac.SetTypeID(r.ID)
}

// Mutation returns the ResourceAccessMutation object of the builder.
func (rac *ResourceAccessCreate) Mutation() *ResourceAccessMutation {
	return rac.mutation
}

// Save creates the ResourceAccess in the database.
func (rac *ResourceAccessCreate) Save(ctx context.Context) (*ResourceAccess, error) {
	rac.defaults()
	return withHooks(ctx, rac.sqlSave, rac.mutation, rac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (rac *ResourceAccessCreate) SaveX(ctx context.Context) *ResourceAccess {
	v, err := rac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (rac *ResourceAccessCreate) Exec(ctx context.Context) error {
	_, err := rac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rac *ResourceAccessCreate) ExecX(ctx context.Context) {
	if err := rac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (rac *ResourceAccessCreate) defaults() {
	if _, ok := rac.mutation.IdentityID(); !ok {
		v := resourceaccess.DefaultIdentityID
		rac.mutation.SetIdentityID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rac *ResourceAccessCreate) check() error {
	if _, ok := rac.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "ResourceAccess.tenant_id"`)}
	}
	if _, ok := rac.mutation.IdentityID(); !ok {
		return &ValidationError{Name: "identity_id", err: errors.New(`ent: missing required field "ResourceAccess.identity_id"`)}
	}
	if _, ok := rac.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "ResourceAccess.role_id"`)}
	}
	if len(rac.mutation.RoleIDs()) == 0 {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "ResourceAccess.role"`)}
	}
	return nil
}

func (rac *ResourceAccessCreate) sqlSave(ctx context.Context) (*ResourceAccess, error) {
	if err := rac.check(); err != nil {
		return nil, err
	}
	_node, _spec := rac.createSpec()
	if err := sqlgraph.CreateNode(ctx, rac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	rac.mutation.id = &_node.ID
	rac.mutation.done = true
	return _node, nil
}

func (rac *ResourceAccessCreate) createSpec() (*ResourceAccess, *sqlgraph.CreateSpec) {
	var (
		_node = &ResourceAccess{config: rac.config}
		_spec = sqlgraph.NewCreateSpec(resourceaccess.Table, sqlgraph.NewFieldSpec(resourceaccess.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = rac.conflict
	if value, ok := rac.mutation.TenantID(); ok {
		_spec.SetField(resourceaccess.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := rac.mutation.ResourceID(); ok {
		_spec.SetField(resourceaccess.FieldResourceID, field.TypeInt64, value)
		_node.ResourceID = &value
	}
	if value, ok := rac.mutation.IdentityID(); ok {
		_spec.SetField(resourceaccess.FieldIdentityID, field.TypeString, value)
		_node.IdentityID = value
	}
	if nodes := rac.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceaccess.RoleTable,
			Columns: []string{resourceaccess.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := rac.mutation.TypeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   resourceaccess.TypeTable,
			Columns: []string{resourceaccess.TypeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(resourcetype.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ResourceType = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceAccess.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceAccessUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (rac *ResourceAccessCreate) OnConflict(opts ...sql.ConflictOption) *ResourceAccessUpsertOne {
	rac.conflict = opts
	return &ResourceAccessUpsertOne{
		create: rac,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (rac *ResourceAccessCreate) OnConflictColumns(columns ...string) *ResourceAccessUpsertOne {
	rac.conflict = append(rac.conflict, sql.ConflictColumns(columns...))
	return &ResourceAccessUpsertOne{
		create: rac,
	}
}

type (
	// ResourceAccessUpsertOne is the builder for "upsert"-ing
	//  one ResourceAccess node.
	ResourceAccessUpsertOne struct {
		create *ResourceAccessCreate
	}

	// ResourceAccessUpsert is the "OnConflict" setter.
	ResourceAccessUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceAccessUpsertOne) UpdateNewValues() *ResourceAccessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(resourceaccess.FieldTenantID)
		}
		if _, exists := u.create.mutation.ResourceType(); exists {
			s.SetIgnore(resourceaccess.FieldResourceType)
		}
		if _, exists := u.create.mutation.ResourceID(); exists {
			s.SetIgnore(resourceaccess.FieldResourceID)
		}
		if _, exists := u.create.mutation.IdentityID(); exists {
			s.SetIgnore(resourceaccess.FieldIdentityID)
		}
		if _, exists := u.create.mutation.RoleID(); exists {
			s.SetIgnore(resourceaccess.FieldRoleID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ResourceAccessUpsertOne) Ignore() *ResourceAccessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceAccessUpsertOne) DoNothing() *ResourceAccessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceAccessCreate.OnConflict
// documentation for more info.
func (u *ResourceAccessUpsertOne) Update(set func(*ResourceAccessUpsert)) *ResourceAccessUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceAccessUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ResourceAccessUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceAccessCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceAccessUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ResourceAccessUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ResourceAccessUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ResourceAccessCreateBulk is the builder for creating many ResourceAccess entities in bulk.
type ResourceAccessCreateBulk struct {
	config
	err      error
	builders []*ResourceAccessCreate
	conflict []sql.ConflictOption
}

// Save creates the ResourceAccess entities in the database.
func (racb *ResourceAccessCreateBulk) Save(ctx context.Context) ([]*ResourceAccess, error) {
	if racb.err != nil {
		return nil, racb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(racb.builders))
	nodes := make([]*ResourceAccess, len(racb.builders))
	mutators := make([]Mutator, len(racb.builders))
	for i := range racb.builders {
		func(i int, root context.Context) {
			builder := racb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ResourceAccessMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, racb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = racb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, racb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, racb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (racb *ResourceAccessCreateBulk) SaveX(ctx context.Context) []*ResourceAccess {
	v, err := racb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (racb *ResourceAccessCreateBulk) Exec(ctx context.Context) error {
	_, err := racb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (racb *ResourceAccessCreateBulk) ExecX(ctx context.Context) {
	if err := racb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ResourceAccess.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ResourceAccessUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (racb *ResourceAccessCreateBulk) OnConflict(opts ...sql.ConflictOption) *ResourceAccessUpsertBulk {
	racb.conflict = opts
	return &ResourceAccessUpsertBulk{
		create: racb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (racb *ResourceAccessCreateBulk) OnConflictColumns(columns ...string) *ResourceAccessUpsertBulk {
	racb.conflict = append(racb.conflict, sql.ConflictColumns(columns...))
	return &ResourceAccessUpsertBulk{
		create: racb,
	}
}

// ResourceAccessUpsertBulk is the builder for "upsert"-ing
// a bulk of ResourceAccess nodes.
type ResourceAccessUpsertBulk struct {
	create *ResourceAccessCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ResourceAccessUpsertBulk) UpdateNewValues() *ResourceAccessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(resourceaccess.FieldTenantID)
			}
			if _, exists := b.mutation.ResourceType(); exists {
				s.SetIgnore(resourceaccess.FieldResourceType)
			}
			if _, exists := b.mutation.ResourceID(); exists {
				s.SetIgnore(resourceaccess.FieldResourceID)
			}
			if _, exists := b.mutation.IdentityID(); exists {
				s.SetIgnore(resourceaccess.FieldIdentityID)
			}
			if _, exists := b.mutation.RoleID(); exists {
				s.SetIgnore(resourceaccess.FieldRoleID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ResourceAccess.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ResourceAccessUpsertBulk) Ignore() *ResourceAccessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ResourceAccessUpsertBulk) DoNothing() *ResourceAccessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ResourceAccessCreateBulk.OnConflict
// documentation for more info.
func (u *ResourceAccessUpsertBulk) Update(set func(*ResourceAccessUpsert)) *ResourceAccessUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ResourceAccessUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *ResourceAccessUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ResourceAccessCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ResourceAccessCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ResourceAccessUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
