// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/makesalekz/rbac/ent/predicate"
	"github.com/makesalekz/rbac/ent/resourceaccess"
)

// ResourceAccessUpdate is the builder for updating ResourceAccess entities.
type ResourceAccessUpdate struct {
	config
	hooks     []Hook
	mutation  *ResourceAccessMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the ResourceAccessUpdate builder.
func (rau *ResourceAccessUpdate) Where(ps ...predicate.ResourceAccess) *ResourceAccessUpdate {
	rau.mutation.Where(ps...)
	return rau
}

// Mutation returns the ResourceAccessMutation object of the builder.
func (rau *ResourceAccessUpdate) Mutation() *ResourceAccessMutation {
	return rau.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (rau *ResourceAccessUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, rau.sqlSave, rau.mutation, rau.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rau *ResourceAccessUpdate) SaveX(ctx context.Context) int {
	affected, err := rau.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (rau *ResourceAccessUpdate) Exec(ctx context.Context) error {
	_, err := rau.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rau *ResourceAccessUpdate) ExecX(ctx context.Context) {
	if err := rau.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rau *ResourceAccessUpdate) check() error {
	if rau.mutation.RoleCleared() && len(rau.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceAccess.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (rau *ResourceAccessUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceAccessUpdate {
	rau.modifiers = append(rau.modifiers, modifiers...)
	return rau
}

func (rau *ResourceAccessUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := rau.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceaccess.Table, resourceaccess.Columns, sqlgraph.NewFieldSpec(resourceaccess.FieldID, field.TypeInt64))
	if ps := rau.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rau.mutation.ResourceIDCleared() {
		_spec.ClearField(resourceaccess.FieldResourceID, field.TypeInt64)
	}
	_spec.AddModifiers(rau.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, rau.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceaccess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	rau.mutation.done = true
	return n, nil
}

// ResourceAccessUpdateOne is the builder for updating a single ResourceAccess entity.
type ResourceAccessUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *ResourceAccessMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Mutation returns the ResourceAccessMutation object of the builder.
func (rauo *ResourceAccessUpdateOne) Mutation() *ResourceAccessMutation {
	return rauo.mutation
}

// Where appends a list predicates to the ResourceAccessUpdate builder.
func (rauo *ResourceAccessUpdateOne) Where(ps ...predicate.ResourceAccess) *ResourceAccessUpdateOne {
	rauo.mutation.Where(ps...)
	return rauo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (rauo *ResourceAccessUpdateOne) Select(field string, fields ...string) *ResourceAccessUpdateOne {
	rauo.fields = append([]string{field}, fields...)
	return rauo
}

// Save executes the query and returns the updated ResourceAccess entity.
func (rauo *ResourceAccessUpdateOne) Save(ctx context.Context) (*ResourceAccess, error) {
	return withHooks(ctx, rauo.sqlSave, rauo.mutation, rauo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (rauo *ResourceAccessUpdateOne) SaveX(ctx context.Context) *ResourceAccess {
	node, err := rauo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (rauo *ResourceAccessUpdateOne) Exec(ctx context.Context) error {
	_, err := rauo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (rauo *ResourceAccessUpdateOne) ExecX(ctx context.Context) {
	if err := rauo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (rauo *ResourceAccessUpdateOne) check() error {
	if rauo.mutation.RoleCleared() && len(rauo.mutation.RoleIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ResourceAccess.role"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (rauo *ResourceAccessUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *ResourceAccessUpdateOne {
	rauo.modifiers = append(rauo.modifiers, modifiers...)
	return rauo
}

func (rauo *ResourceAccessUpdateOne) sqlSave(ctx context.Context) (_node *ResourceAccess, err error) {
	if err := rauo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(resourceaccess.Table, resourceaccess.Columns, sqlgraph.NewFieldSpec(resourceaccess.FieldID, field.TypeInt64))
	id, ok := rauo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ResourceAccess.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := rauo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, resourceaccess.FieldID)
		for _, f := range fields {
			if !resourceaccess.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != resourceaccess.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := rauo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if rauo.mutation.ResourceIDCleared() {
		_spec.ClearField(resourceaccess.FieldResourceID, field.TypeInt64)
	}
	_spec.AddModifiers(rauo.modifiers...)
	_node = &ResourceAccess{config: rauo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, rauo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{resourceaccess.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	rauo.mutation.done = true
	return _node, nil
}
