// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"gitlab.calendaria.team/services/rbac/ent/resourcetype"
)

// ResourceType is the model entity for the ResourceType schema.
type ResourceType struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ResourceTypeQuery when eager-loading is set.
	Edges        ResourceTypeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ResourceTypeEdges holds the relations/edges for other nodes in the graph.
type ResourceTypeEdges struct {
	// Roles holds the value of the roles edge.
	Roles []*Role `json:"roles,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RolesOrErr returns the Roles value or an error if the edge
// was not loaded in eager-loading.
func (e ResourceTypeEdges) RolesOrErr() ([]*Role, error) {
	if e.loadedTypes[0] {
		return e.Roles, nil
	}
	return nil, &NotLoadedError{edge: "roles"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ResourceType) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case resourcetype.FieldID, resourcetype.FieldDescription:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ResourceType fields.
func (rt *ResourceType) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case resourcetype.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				rt.ID = value.String
			}
		case resourcetype.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				rt.Description = value.String
			}
		default:
			rt.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ResourceType.
// This includes values selected through modifiers, order, etc.
func (rt *ResourceType) Value(name string) (ent.Value, error) {
	return rt.selectValues.Get(name)
}

// QueryRoles queries the "roles" edge of the ResourceType entity.
func (rt *ResourceType) QueryRoles() *RoleQuery {
	return NewResourceTypeClient(rt.config).QueryRoles(rt)
}

// Update returns a builder for updating this ResourceType.
// Note that you need to call ResourceType.Unwrap() before calling this method if this ResourceType
// was returned from a transaction, and the transaction was committed or rolled back.
func (rt *ResourceType) Update() *ResourceTypeUpdateOne {
	return NewResourceTypeClient(rt.config).UpdateOne(rt)
}

// Unwrap unwraps the ResourceType entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (rt *ResourceType) Unwrap() *ResourceType {
	_tx, ok := rt.config.driver.(*txDriver)
	if !ok {
		panic("ent: ResourceType is not a transactional entity")
	}
	rt.config.driver = _tx.drv
	return rt
}

// String implements the fmt.Stringer.
func (rt *ResourceType) String() string {
	var builder strings.Builder
	builder.WriteString("ResourceType(")
	builder.WriteString(fmt.Sprintf("id=%v, ", rt.ID))
	builder.WriteString("description=")
	builder.WriteString(rt.Description)
	builder.WriteByte(')')
	return builder.String()
}

// ResourceTypes is a parsable slice of ResourceType.
type ResourceTypes []*ResourceType
