// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/rbac/ent/predicate"
	"gitlab.calendaria.team/services/rbac/ent/role"
	"gitlab.calendaria.team/services/rbac/ent/team"
	"gitlab.calendaria.team/services/rbac/ent/teamidentityrole"
)

// TeamIdentityRoleQuery is the builder for querying TeamIdentityRole entities.
type TeamIdentityRoleQuery struct {
	config
	ctx        *QueryContext
	order      []teamidentityrole.OrderOption
	inters     []Interceptor
	predicates []predicate.TeamIdentityRole
	withRole   *RoleQuery
	withTeam   *TeamQuery
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TeamIdentityRoleQuery builder.
func (tirq *TeamIdentityRoleQuery) Where(ps ...predicate.TeamIdentityRole) *TeamIdentityRoleQuery {
	tirq.predicates = append(tirq.predicates, ps...)
	return tirq
}

// Limit the number of records to be returned by this query.
func (tirq *TeamIdentityRoleQuery) Limit(limit int) *TeamIdentityRoleQuery {
	tirq.ctx.Limit = &limit
	return tirq
}

// Offset to start from.
func (tirq *TeamIdentityRoleQuery) Offset(offset int) *TeamIdentityRoleQuery {
	tirq.ctx.Offset = &offset
	return tirq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tirq *TeamIdentityRoleQuery) Unique(unique bool) *TeamIdentityRoleQuery {
	tirq.ctx.Unique = &unique
	return tirq
}

// Order specifies how the records should be ordered.
func (tirq *TeamIdentityRoleQuery) Order(o ...teamidentityrole.OrderOption) *TeamIdentityRoleQuery {
	tirq.order = append(tirq.order, o...)
	return tirq
}

// QueryRole chains the current query on the "role" edge.
func (tirq *TeamIdentityRoleQuery) QueryRole() *RoleQuery {
	query := (&RoleClient{config: tirq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tirq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tirq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamidentityrole.Table, teamidentityrole.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamidentityrole.RoleTable, teamidentityrole.RoleColumn),
		)
		fromU = sqlgraph.SetNeighbors(tirq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTeam chains the current query on the "team" edge.
func (tirq *TeamIdentityRoleQuery) QueryTeam() *TeamQuery {
	query := (&TeamClient{config: tirq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tirq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tirq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(teamidentityrole.Table, teamidentityrole.FieldID, selector),
			sqlgraph.To(team.Table, team.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, teamidentityrole.TeamTable, teamidentityrole.TeamColumn),
		)
		fromU = sqlgraph.SetNeighbors(tirq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first TeamIdentityRole entity from the query.
// Returns a *NotFoundError when no TeamIdentityRole was found.
func (tirq *TeamIdentityRoleQuery) First(ctx context.Context) (*TeamIdentityRole, error) {
	nodes, err := tirq.Limit(1).All(setContextOp(ctx, tirq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{teamidentityrole.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) FirstX(ctx context.Context) *TeamIdentityRole {
	node, err := tirq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first TeamIdentityRole ID from the query.
// Returns a *NotFoundError when no TeamIdentityRole ID was found.
func (tirq *TeamIdentityRoleQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tirq.Limit(1).IDs(setContextOp(ctx, tirq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{teamidentityrole.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) FirstIDX(ctx context.Context) int64 {
	id, err := tirq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single TeamIdentityRole entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one TeamIdentityRole entity is found.
// Returns a *NotFoundError when no TeamIdentityRole entities are found.
func (tirq *TeamIdentityRoleQuery) Only(ctx context.Context) (*TeamIdentityRole, error) {
	nodes, err := tirq.Limit(2).All(setContextOp(ctx, tirq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{teamidentityrole.Label}
	default:
		return nil, &NotSingularError{teamidentityrole.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) OnlyX(ctx context.Context) *TeamIdentityRole {
	node, err := tirq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only TeamIdentityRole ID in the query.
// Returns a *NotSingularError when more than one TeamIdentityRole ID is found.
// Returns a *NotFoundError when no entities are found.
func (tirq *TeamIdentityRoleQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = tirq.Limit(2).IDs(setContextOp(ctx, tirq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{teamidentityrole.Label}
	default:
		err = &NotSingularError{teamidentityrole.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := tirq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of TeamIdentityRoles.
func (tirq *TeamIdentityRoleQuery) All(ctx context.Context) ([]*TeamIdentityRole, error) {
	ctx = setContextOp(ctx, tirq.ctx, ent.OpQueryAll)
	if err := tirq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*TeamIdentityRole, *TeamIdentityRoleQuery]()
	return withInterceptors[[]*TeamIdentityRole](ctx, tirq, qr, tirq.inters)
}

// AllX is like All, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) AllX(ctx context.Context) []*TeamIdentityRole {
	nodes, err := tirq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of TeamIdentityRole IDs.
func (tirq *TeamIdentityRoleQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if tirq.ctx.Unique == nil && tirq.path != nil {
		tirq.Unique(true)
	}
	ctx = setContextOp(ctx, tirq.ctx, ent.OpQueryIDs)
	if err = tirq.Select(teamidentityrole.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) IDsX(ctx context.Context) []int64 {
	ids, err := tirq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tirq *TeamIdentityRoleQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, tirq.ctx, ent.OpQueryCount)
	if err := tirq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, tirq, querierCount[*TeamIdentityRoleQuery](), tirq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) CountX(ctx context.Context) int {
	count, err := tirq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tirq *TeamIdentityRoleQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, tirq.ctx, ent.OpQueryExist)
	switch _, err := tirq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (tirq *TeamIdentityRoleQuery) ExistX(ctx context.Context) bool {
	exist, err := tirq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TeamIdentityRoleQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tirq *TeamIdentityRoleQuery) Clone() *TeamIdentityRoleQuery {
	if tirq == nil {
		return nil
	}
	return &TeamIdentityRoleQuery{
		config:     tirq.config,
		ctx:        tirq.ctx.Clone(),
		order:      append([]teamidentityrole.OrderOption{}, tirq.order...),
		inters:     append([]Interceptor{}, tirq.inters...),
		predicates: append([]predicate.TeamIdentityRole{}, tirq.predicates...),
		withRole:   tirq.withRole.Clone(),
		withTeam:   tirq.withTeam.Clone(),
		// clone intermediate query.
		sql:       tirq.sql.Clone(),
		path:      tirq.path,
		modifiers: append([]func(*sql.Selector){}, tirq.modifiers...),
	}
}

// WithRole tells the query-builder to eager-load the nodes that are connected to
// the "role" edge. The optional arguments are used to configure the query builder of the edge.
func (tirq *TeamIdentityRoleQuery) WithRole(opts ...func(*RoleQuery)) *TeamIdentityRoleQuery {
	query := (&RoleClient{config: tirq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tirq.withRole = query
	return tirq
}

// WithTeam tells the query-builder to eager-load the nodes that are connected to
// the "team" edge. The optional arguments are used to configure the query builder of the edge.
func (tirq *TeamIdentityRoleQuery) WithTeam(opts ...func(*TeamQuery)) *TeamIdentityRoleQuery {
	query := (&TeamClient{config: tirq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	tirq.withTeam = query
	return tirq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.TeamIdentityRole.Query().
//		GroupBy(teamidentityrole.FieldTenantID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (tirq *TeamIdentityRoleQuery) GroupBy(field string, fields ...string) *TeamIdentityRoleGroupBy {
	tirq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &TeamIdentityRoleGroupBy{build: tirq}
	grbuild.flds = &tirq.ctx.Fields
	grbuild.label = teamidentityrole.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		TenantID int64 `json:"tenant_id,omitempty"`
//	}
//
//	client.TeamIdentityRole.Query().
//		Select(teamidentityrole.FieldTenantID).
//		Scan(ctx, &v)
func (tirq *TeamIdentityRoleQuery) Select(fields ...string) *TeamIdentityRoleSelect {
	tirq.ctx.Fields = append(tirq.ctx.Fields, fields...)
	sbuild := &TeamIdentityRoleSelect{TeamIdentityRoleQuery: tirq}
	sbuild.label = teamidentityrole.Label
	sbuild.flds, sbuild.scan = &tirq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a TeamIdentityRoleSelect configured with the given aggregations.
func (tirq *TeamIdentityRoleQuery) Aggregate(fns ...AggregateFunc) *TeamIdentityRoleSelect {
	return tirq.Select().Aggregate(fns...)
}

func (tirq *TeamIdentityRoleQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range tirq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, tirq); err != nil {
				return err
			}
		}
	}
	for _, f := range tirq.ctx.Fields {
		if !teamidentityrole.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tirq.path != nil {
		prev, err := tirq.path(ctx)
		if err != nil {
			return err
		}
		tirq.sql = prev
	}
	return nil
}

func (tirq *TeamIdentityRoleQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*TeamIdentityRole, error) {
	var (
		nodes       = []*TeamIdentityRole{}
		_spec       = tirq.querySpec()
		loadedTypes = [2]bool{
			tirq.withRole != nil,
			tirq.withTeam != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*TeamIdentityRole).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &TeamIdentityRole{config: tirq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(tirq.modifiers) > 0 {
		_spec.Modifiers = tirq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, tirq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := tirq.withRole; query != nil {
		if err := tirq.loadRole(ctx, query, nodes, nil,
			func(n *TeamIdentityRole, e *Role) { n.Edges.Role = e }); err != nil {
			return nil, err
		}
	}
	if query := tirq.withTeam; query != nil {
		if err := tirq.loadTeam(ctx, query, nodes, nil,
			func(n *TeamIdentityRole, e *Team) { n.Edges.Team = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (tirq *TeamIdentityRoleQuery) loadRole(ctx context.Context, query *RoleQuery, nodes []*TeamIdentityRole, init func(*TeamIdentityRole), assign func(*TeamIdentityRole, *Role)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*TeamIdentityRole)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (tirq *TeamIdentityRoleQuery) loadTeam(ctx context.Context, query *TeamQuery, nodes []*TeamIdentityRole, init func(*TeamIdentityRole), assign func(*TeamIdentityRole, *Team)) error {
	ids := make([]int64, 0, len(nodes))
	nodeids := make(map[int64][]*TeamIdentityRole)
	for i := range nodes {
		if nodes[i].TeamID == nil {
			continue
		}
		fk := *nodes[i].TeamID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(team.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "team_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (tirq *TeamIdentityRoleQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tirq.querySpec()
	if len(tirq.modifiers) > 0 {
		_spec.Modifiers = tirq.modifiers
	}
	_spec.Node.Columns = tirq.ctx.Fields
	if len(tirq.ctx.Fields) > 0 {
		_spec.Unique = tirq.ctx.Unique != nil && *tirq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, tirq.driver, _spec)
}

func (tirq *TeamIdentityRoleQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(teamidentityrole.Table, teamidentityrole.Columns, sqlgraph.NewFieldSpec(teamidentityrole.FieldID, field.TypeInt64))
	_spec.From = tirq.sql
	if unique := tirq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if tirq.path != nil {
		_spec.Unique = true
	}
	if fields := tirq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, teamidentityrole.FieldID)
		for i := range fields {
			if fields[i] != teamidentityrole.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if tirq.withRole != nil {
			_spec.Node.AddColumnOnce(teamidentityrole.FieldRoleID)
		}
		if tirq.withTeam != nil {
			_spec.Node.AddColumnOnce(teamidentityrole.FieldTeamID)
		}
	}
	if ps := tirq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tirq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tirq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tirq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tirq *TeamIdentityRoleQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tirq.driver.Dialect())
	t1 := builder.Table(teamidentityrole.Table)
	columns := tirq.ctx.Fields
	if len(columns) == 0 {
		columns = teamidentityrole.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tirq.sql != nil {
		selector = tirq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tirq.ctx.Unique != nil && *tirq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range tirq.modifiers {
		m(selector)
	}
	for _, p := range tirq.predicates {
		p(selector)
	}
	for _, p := range tirq.order {
		p(selector)
	}
	if offset := tirq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tirq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tirq *TeamIdentityRoleQuery) Modify(modifiers ...func(s *sql.Selector)) *TeamIdentityRoleSelect {
	tirq.modifiers = append(tirq.modifiers, modifiers...)
	return tirq.Select()
}

// TeamIdentityRoleGroupBy is the group-by builder for TeamIdentityRole entities.
type TeamIdentityRoleGroupBy struct {
	selector
	build *TeamIdentityRoleQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tirgb *TeamIdentityRoleGroupBy) Aggregate(fns ...AggregateFunc) *TeamIdentityRoleGroupBy {
	tirgb.fns = append(tirgb.fns, fns...)
	return tirgb
}

// Scan applies the selector query and scans the result into the given value.
func (tirgb *TeamIdentityRoleGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tirgb.build.ctx, ent.OpQueryGroupBy)
	if err := tirgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamIdentityRoleQuery, *TeamIdentityRoleGroupBy](ctx, tirgb.build, tirgb, tirgb.build.inters, v)
}

func (tirgb *TeamIdentityRoleGroupBy) sqlScan(ctx context.Context, root *TeamIdentityRoleQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(tirgb.fns))
	for _, fn := range tirgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*tirgb.flds)+len(tirgb.fns))
		for _, f := range *tirgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*tirgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tirgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// TeamIdentityRoleSelect is the builder for selecting fields of TeamIdentityRole entities.
type TeamIdentityRoleSelect struct {
	*TeamIdentityRoleQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (tirs *TeamIdentityRoleSelect) Aggregate(fns ...AggregateFunc) *TeamIdentityRoleSelect {
	tirs.fns = append(tirs.fns, fns...)
	return tirs
}

// Scan applies the selector query and scans the result into the given value.
func (tirs *TeamIdentityRoleSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, tirs.ctx, ent.OpQuerySelect)
	if err := tirs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*TeamIdentityRoleQuery, *TeamIdentityRoleSelect](ctx, tirs.TeamIdentityRoleQuery, tirs, tirs.inters, v)
}

func (tirs *TeamIdentityRoleSelect) sqlScan(ctx context.Context, root *TeamIdentityRoleQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(tirs.fns))
	for _, fn := range tirs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*tirs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tirs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (tirs *TeamIdentityRoleSelect) Modify(modifiers ...func(s *sql.Selector)) *TeamIdentityRoleSelect {
	tirs.modifiers = append(tirs.modifiers, modifiers...)
	return tirs
}
