// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"rbac/ent/predicate"
	"rbac/ent/teamidentityrole"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TeamIdentityRoleDelete is the builder for deleting a TeamIdentityRole entity.
type TeamIdentityRoleDelete struct {
	config
	hooks    []Hook
	mutation *TeamIdentityRoleMutation
}

// Where appends a list predicates to the TeamIdentityRoleDelete builder.
func (tird *TeamIdentityRoleDelete) Where(ps ...predicate.TeamIdentityRole) *TeamIdentityRoleDelete {
	tird.mutation.Where(ps...)
	return tird
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (tird *TeamIdentityRoleDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, tird.sqlExec, tird.mutation, tird.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (tird *TeamIdentityRoleDelete) ExecX(ctx context.Context) int {
	n, err := tird.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (tird *TeamIdentityRoleDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(teamidentityrole.Table, sqlgraph.NewFieldSpec(teamidentityrole.FieldID, field.TypeInt64))
	if ps := tird.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, tird.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	tird.mutation.done = true
	return affected, err
}

// TeamIdentityRoleDeleteOne is the builder for deleting a single TeamIdentityRole entity.
type TeamIdentityRoleDeleteOne struct {
	tird *TeamIdentityRoleDelete
}

// Where appends a list predicates to the TeamIdentityRoleDelete builder.
func (tirdo *TeamIdentityRoleDeleteOne) Where(ps ...predicate.TeamIdentityRole) *TeamIdentityRoleDeleteOne {
	tirdo.tird.mutation.Where(ps...)
	return tirdo
}

// Exec executes the deletion query.
func (tirdo *TeamIdentityRoleDeleteOne) Exec(ctx context.Context) error {
	n, err := tirdo.tird.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{teamidentityrole.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (tirdo *TeamIdentityRoleDeleteOne) ExecX(ctx context.Context) {
	if err := tirdo.Exec(ctx); err != nil {
		panic(err)
	}
}
