// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"gitlab.calendaria.team/services/rbac/ent/role"
	"gitlab.calendaria.team/services/rbac/ent/team"
	"gitlab.calendaria.team/services/rbac/ent/teamidentityrole"
)

// TeamIdentityRoleCreate is the builder for creating a TeamIdentityRole entity.
type TeamIdentityRoleCreate struct {
	config
	mutation *TeamIdentityRoleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTenantID sets the "tenant_id" field.
func (tirc *TeamIdentityRoleCreate) SetTenantID(i int64) *TeamIdentityRoleCreate {
	tirc.mutation.SetTenantID(i)
	return tirc
}

// SetTeamID sets the "team_id" field.
func (tirc *TeamIdentityRoleCreate) SetTeamID(i int64) *TeamIdentityRoleCreate {
	tirc.mutation.SetTeamID(i)
	return tirc
}

// SetNillableTeamID sets the "team_id" field if the given value is not nil.
func (tirc *TeamIdentityRoleCreate) SetNillableTeamID(i *int64) *TeamIdentityRoleCreate {
	if i != nil {
		tirc.SetTeamID(*i)
	}
	return tirc
}

// SetIdentityID sets the "identity_id" field.
func (tirc *TeamIdentityRoleCreate) SetIdentityID(s string) *TeamIdentityRoleCreate {
	tirc.mutation.SetIdentityID(s)
	return tirc
}

// SetNillableIdentityID sets the "identity_id" field if the given value is not nil.
func (tirc *TeamIdentityRoleCreate) SetNillableIdentityID(s *string) *TeamIdentityRoleCreate {
	if s != nil {
		tirc.SetIdentityID(*s)
	}
	return tirc
}

// SetRoleID sets the "role_id" field.
func (tirc *TeamIdentityRoleCreate) SetRoleID(i int64) *TeamIdentityRoleCreate {
	tirc.mutation.SetRoleID(i)
	return tirc
}

// SetRole sets the "role" edge to the Role entity.
func (tirc *TeamIdentityRoleCreate) SetRole(r *Role) *TeamIdentityRoleCreate {
	return tirc.SetRoleID(r.ID)
}

// SetTeam sets the "team" edge to the Team entity.
func (tirc *TeamIdentityRoleCreate) SetTeam(t *Team) *TeamIdentityRoleCreate {
	return tirc.SetTeamID(t.ID)
}

// Mutation returns the TeamIdentityRoleMutation object of the builder.
func (tirc *TeamIdentityRoleCreate) Mutation() *TeamIdentityRoleMutation {
	return tirc.mutation
}

// Save creates the TeamIdentityRole in the database.
func (tirc *TeamIdentityRoleCreate) Save(ctx context.Context) (*TeamIdentityRole, error) {
	tirc.defaults()
	return withHooks(ctx, tirc.sqlSave, tirc.mutation, tirc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (tirc *TeamIdentityRoleCreate) SaveX(ctx context.Context) *TeamIdentityRole {
	v, err := tirc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tirc *TeamIdentityRoleCreate) Exec(ctx context.Context) error {
	_, err := tirc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tirc *TeamIdentityRoleCreate) ExecX(ctx context.Context) {
	if err := tirc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tirc *TeamIdentityRoleCreate) defaults() {
	if _, ok := tirc.mutation.TeamID(); !ok {
		v := teamidentityrole.DefaultTeamID
		tirc.mutation.SetTeamID(v)
	}
	if _, ok := tirc.mutation.IdentityID(); !ok {
		v := teamidentityrole.DefaultIdentityID
		tirc.mutation.SetIdentityID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tirc *TeamIdentityRoleCreate) check() error {
	if _, ok := tirc.mutation.TenantID(); !ok {
		return &ValidationError{Name: "tenant_id", err: errors.New(`ent: missing required field "TeamIdentityRole.tenant_id"`)}
	}
	if _, ok := tirc.mutation.IdentityID(); !ok {
		return &ValidationError{Name: "identity_id", err: errors.New(`ent: missing required field "TeamIdentityRole.identity_id"`)}
	}
	if _, ok := tirc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role_id", err: errors.New(`ent: missing required field "TeamIdentityRole.role_id"`)}
	}
	if _, ok := tirc.mutation.RoleID(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required edge "TeamIdentityRole.role"`)}
	}
	return nil
}

func (tirc *TeamIdentityRoleCreate) sqlSave(ctx context.Context) (*TeamIdentityRole, error) {
	if err := tirc.check(); err != nil {
		return nil, err
	}
	_node, _spec := tirc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tirc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	tirc.mutation.id = &_node.ID
	tirc.mutation.done = true
	return _node, nil
}

func (tirc *TeamIdentityRoleCreate) createSpec() (*TeamIdentityRole, *sqlgraph.CreateSpec) {
	var (
		_node = &TeamIdentityRole{config: tirc.config}
		_spec = sqlgraph.NewCreateSpec(teamidentityrole.Table, sqlgraph.NewFieldSpec(teamidentityrole.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = tirc.conflict
	if value, ok := tirc.mutation.TenantID(); ok {
		_spec.SetField(teamidentityrole.FieldTenantID, field.TypeInt64, value)
		_node.TenantID = value
	}
	if value, ok := tirc.mutation.IdentityID(); ok {
		_spec.SetField(teamidentityrole.FieldIdentityID, field.TypeString, value)
		_node.IdentityID = value
	}
	if nodes := tirc.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamidentityrole.RoleTable,
			Columns: []string{teamidentityrole.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.RoleID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := tirc.mutation.TeamIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   teamidentityrole.TeamTable,
			Columns: []string{teamidentityrole.TeamColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(team.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TeamID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamIdentityRole.Create().
//		SetTenantID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamIdentityRoleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (tirc *TeamIdentityRoleCreate) OnConflict(opts ...sql.ConflictOption) *TeamIdentityRoleUpsertOne {
	tirc.conflict = opts
	return &TeamIdentityRoleUpsertOne{
		create: tirc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tirc *TeamIdentityRoleCreate) OnConflictColumns(columns ...string) *TeamIdentityRoleUpsertOne {
	tirc.conflict = append(tirc.conflict, sql.ConflictColumns(columns...))
	return &TeamIdentityRoleUpsertOne{
		create: tirc,
	}
}

type (
	// TeamIdentityRoleUpsertOne is the builder for "upsert"-ing
	//  one TeamIdentityRole node.
	TeamIdentityRoleUpsertOne struct {
		create *TeamIdentityRoleCreate
	}

	// TeamIdentityRoleUpsert is the "OnConflict" setter.
	TeamIdentityRoleUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamIdentityRoleUpsertOne) UpdateNewValues() *TeamIdentityRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.TenantID(); exists {
			s.SetIgnore(teamidentityrole.FieldTenantID)
		}
		if _, exists := u.create.mutation.TeamID(); exists {
			s.SetIgnore(teamidentityrole.FieldTeamID)
		}
		if _, exists := u.create.mutation.IdentityID(); exists {
			s.SetIgnore(teamidentityrole.FieldIdentityID)
		}
		if _, exists := u.create.mutation.RoleID(); exists {
			s.SetIgnore(teamidentityrole.FieldRoleID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TeamIdentityRoleUpsertOne) Ignore() *TeamIdentityRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamIdentityRoleUpsertOne) DoNothing() *TeamIdentityRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamIdentityRoleCreate.OnConflict
// documentation for more info.
func (u *TeamIdentityRoleUpsertOne) Update(set func(*TeamIdentityRoleUpsert)) *TeamIdentityRoleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamIdentityRoleUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *TeamIdentityRoleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamIdentityRoleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamIdentityRoleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TeamIdentityRoleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TeamIdentityRoleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TeamIdentityRoleCreateBulk is the builder for creating many TeamIdentityRole entities in bulk.
type TeamIdentityRoleCreateBulk struct {
	config
	err      error
	builders []*TeamIdentityRoleCreate
	conflict []sql.ConflictOption
}

// Save creates the TeamIdentityRole entities in the database.
func (tircb *TeamIdentityRoleCreateBulk) Save(ctx context.Context) ([]*TeamIdentityRole, error) {
	if tircb.err != nil {
		return nil, tircb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(tircb.builders))
	nodes := make([]*TeamIdentityRole, len(tircb.builders))
	mutators := make([]Mutator, len(tircb.builders))
	for i := range tircb.builders {
		func(i int, root context.Context) {
			builder := tircb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TeamIdentityRoleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tircb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = tircb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tircb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tircb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tircb *TeamIdentityRoleCreateBulk) SaveX(ctx context.Context) []*TeamIdentityRole {
	v, err := tircb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tircb *TeamIdentityRoleCreateBulk) Exec(ctx context.Context) error {
	_, err := tircb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tircb *TeamIdentityRoleCreateBulk) ExecX(ctx context.Context) {
	if err := tircb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TeamIdentityRole.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TeamIdentityRoleUpsert) {
//			SetTenantID(v+v).
//		}).
//		Exec(ctx)
func (tircb *TeamIdentityRoleCreateBulk) OnConflict(opts ...sql.ConflictOption) *TeamIdentityRoleUpsertBulk {
	tircb.conflict = opts
	return &TeamIdentityRoleUpsertBulk{
		create: tircb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (tircb *TeamIdentityRoleCreateBulk) OnConflictColumns(columns ...string) *TeamIdentityRoleUpsertBulk {
	tircb.conflict = append(tircb.conflict, sql.ConflictColumns(columns...))
	return &TeamIdentityRoleUpsertBulk{
		create: tircb,
	}
}

// TeamIdentityRoleUpsertBulk is the builder for "upsert"-ing
// a bulk of TeamIdentityRole nodes.
type TeamIdentityRoleUpsertBulk struct {
	create *TeamIdentityRoleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TeamIdentityRoleUpsertBulk) UpdateNewValues() *TeamIdentityRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.TenantID(); exists {
				s.SetIgnore(teamidentityrole.FieldTenantID)
			}
			if _, exists := b.mutation.TeamID(); exists {
				s.SetIgnore(teamidentityrole.FieldTeamID)
			}
			if _, exists := b.mutation.IdentityID(); exists {
				s.SetIgnore(teamidentityrole.FieldIdentityID)
			}
			if _, exists := b.mutation.RoleID(); exists {
				s.SetIgnore(teamidentityrole.FieldRoleID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TeamIdentityRole.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TeamIdentityRoleUpsertBulk) Ignore() *TeamIdentityRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TeamIdentityRoleUpsertBulk) DoNothing() *TeamIdentityRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TeamIdentityRoleCreateBulk.OnConflict
// documentation for more info.
func (u *TeamIdentityRoleUpsertBulk) Update(set func(*TeamIdentityRoleUpsert)) *TeamIdentityRoleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TeamIdentityRoleUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *TeamIdentityRoleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TeamIdentityRoleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TeamIdentityRoleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TeamIdentityRoleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
