// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"rbac/ent/predicate"
	"rbac/ent/role"
	"rbac/ent/usersroles"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersRolesUpdate is the builder for updating UsersRoles entities.
type UsersRolesUpdate struct {
	config
	hooks     []Hook
	mutation  *UsersRolesMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the UsersRolesUpdate builder.
func (uru *UsersRolesUpdate) Where(ps ...predicate.UsersRoles) *UsersRolesUpdate {
	uru.mutation.Where(ps...)
	return uru
}

// SetUserID sets the "user_id" field.
func (uru *UsersRolesUpdate) SetUserID(i int64) *UsersRolesUpdate {
	uru.mutation.ResetUserID()
	uru.mutation.SetUserID(i)
	return uru
}

// AddUserID adds i to the "user_id" field.
func (uru *UsersRolesUpdate) AddUserID(i int64) *UsersRolesUpdate {
	uru.mutation.AddUserID(i)
	return uru
}

// SetRoleID sets the "role_id" field.
func (uru *UsersRolesUpdate) SetRoleID(i int64) *UsersRolesUpdate {
	uru.mutation.SetRoleID(i)
	return uru
}

// SetTeamID sets the "team_id" field.
func (uru *UsersRolesUpdate) SetTeamID(i int64) *UsersRolesUpdate {
	uru.mutation.SetTeamID(i)
	return uru
}

// SetRole sets the "role" edge to the Role entity.
func (uru *UsersRolesUpdate) SetRole(r *Role) *UsersRolesUpdate {
	return uru.SetRoleID(r.ID)
}

// SetTeamsID sets the "teams" edge to the Role entity by ID.
func (uru *UsersRolesUpdate) SetTeamsID(id int64) *UsersRolesUpdate {
	uru.mutation.SetTeamsID(id)
	return uru
}

// SetTeams sets the "teams" edge to the Role entity.
func (uru *UsersRolesUpdate) SetTeams(r *Role) *UsersRolesUpdate {
	return uru.SetTeamsID(r.ID)
}

// Mutation returns the UsersRolesMutation object of the builder.
func (uru *UsersRolesUpdate) Mutation() *UsersRolesMutation {
	return uru.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (uru *UsersRolesUpdate) ClearRole() *UsersRolesUpdate {
	uru.mutation.ClearRole()
	return uru
}

// ClearTeams clears the "teams" edge to the Role entity.
func (uru *UsersRolesUpdate) ClearTeams() *UsersRolesUpdate {
	uru.mutation.ClearTeams()
	return uru
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (uru *UsersRolesUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, uru.sqlSave, uru.mutation, uru.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uru *UsersRolesUpdate) SaveX(ctx context.Context) int {
	affected, err := uru.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (uru *UsersRolesUpdate) Exec(ctx context.Context) error {
	_, err := uru.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uru *UsersRolesUpdate) ExecX(ctx context.Context) {
	if err := uru.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uru *UsersRolesUpdate) check() error {
	if _, ok := uru.mutation.RoleID(); uru.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersRoles.role"`)
	}
	if _, ok := uru.mutation.TeamsID(); uru.mutation.TeamsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersRoles.teams"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (uru *UsersRolesUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsersRolesUpdate {
	uru.modifiers = append(uru.modifiers, modifiers...)
	return uru
}

func (uru *UsersRolesUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := uru.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersroles.Table, usersroles.Columns, sqlgraph.NewFieldSpec(usersroles.FieldID, field.TypeInt64))
	if ps := uru.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uru.mutation.UserID(); ok {
		_spec.SetField(usersroles.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uru.mutation.AddedUserID(); ok {
		_spec.AddField(usersroles.FieldUserID, field.TypeInt64, value)
	}
	if uru.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.RoleTable,
			Columns: []string{usersroles.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.RoleTable,
			Columns: []string{usersroles.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uru.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.TeamsTable,
			Columns: []string{usersroles.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uru.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.TeamsTable,
			Columns: []string{usersroles.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(uru.modifiers...)
	if n, err = sqlgraph.UpdateNodes(ctx, uru.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersroles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	uru.mutation.done = true
	return n, nil
}

// UsersRolesUpdateOne is the builder for updating a single UsersRoles entity.
type UsersRolesUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *UsersRolesMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUserID sets the "user_id" field.
func (uruo *UsersRolesUpdateOne) SetUserID(i int64) *UsersRolesUpdateOne {
	uruo.mutation.ResetUserID()
	uruo.mutation.SetUserID(i)
	return uruo
}

// AddUserID adds i to the "user_id" field.
func (uruo *UsersRolesUpdateOne) AddUserID(i int64) *UsersRolesUpdateOne {
	uruo.mutation.AddUserID(i)
	return uruo
}

// SetRoleID sets the "role_id" field.
func (uruo *UsersRolesUpdateOne) SetRoleID(i int64) *UsersRolesUpdateOne {
	uruo.mutation.SetRoleID(i)
	return uruo
}

// SetTeamID sets the "team_id" field.
func (uruo *UsersRolesUpdateOne) SetTeamID(i int64) *UsersRolesUpdateOne {
	uruo.mutation.SetTeamID(i)
	return uruo
}

// SetRole sets the "role" edge to the Role entity.
func (uruo *UsersRolesUpdateOne) SetRole(r *Role) *UsersRolesUpdateOne {
	return uruo.SetRoleID(r.ID)
}

// SetTeamsID sets the "teams" edge to the Role entity by ID.
func (uruo *UsersRolesUpdateOne) SetTeamsID(id int64) *UsersRolesUpdateOne {
	uruo.mutation.SetTeamsID(id)
	return uruo
}

// SetTeams sets the "teams" edge to the Role entity.
func (uruo *UsersRolesUpdateOne) SetTeams(r *Role) *UsersRolesUpdateOne {
	return uruo.SetTeamsID(r.ID)
}

// Mutation returns the UsersRolesMutation object of the builder.
func (uruo *UsersRolesUpdateOne) Mutation() *UsersRolesMutation {
	return uruo.mutation
}

// ClearRole clears the "role" edge to the Role entity.
func (uruo *UsersRolesUpdateOne) ClearRole() *UsersRolesUpdateOne {
	uruo.mutation.ClearRole()
	return uruo
}

// ClearTeams clears the "teams" edge to the Role entity.
func (uruo *UsersRolesUpdateOne) ClearTeams() *UsersRolesUpdateOne {
	uruo.mutation.ClearTeams()
	return uruo
}

// Where appends a list predicates to the UsersRolesUpdate builder.
func (uruo *UsersRolesUpdateOne) Where(ps ...predicate.UsersRoles) *UsersRolesUpdateOne {
	uruo.mutation.Where(ps...)
	return uruo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (uruo *UsersRolesUpdateOne) Select(field string, fields ...string) *UsersRolesUpdateOne {
	uruo.fields = append([]string{field}, fields...)
	return uruo
}

// Save executes the query and returns the updated UsersRoles entity.
func (uruo *UsersRolesUpdateOne) Save(ctx context.Context) (*UsersRoles, error) {
	return withHooks(ctx, uruo.sqlSave, uruo.mutation, uruo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (uruo *UsersRolesUpdateOne) SaveX(ctx context.Context) *UsersRoles {
	node, err := uruo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (uruo *UsersRolesUpdateOne) Exec(ctx context.Context) error {
	_, err := uruo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (uruo *UsersRolesUpdateOne) ExecX(ctx context.Context) {
	if err := uruo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (uruo *UsersRolesUpdateOne) check() error {
	if _, ok := uruo.mutation.RoleID(); uruo.mutation.RoleCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersRoles.role"`)
	}
	if _, ok := uruo.mutation.TeamsID(); uruo.mutation.TeamsCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "UsersRoles.teams"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (uruo *UsersRolesUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *UsersRolesUpdateOne {
	uruo.modifiers = append(uruo.modifiers, modifiers...)
	return uruo
}

func (uruo *UsersRolesUpdateOne) sqlSave(ctx context.Context) (_node *UsersRoles, err error) {
	if err := uruo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(usersroles.Table, usersroles.Columns, sqlgraph.NewFieldSpec(usersroles.FieldID, field.TypeInt64))
	id, ok := uruo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UsersRoles.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := uruo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersroles.FieldID)
		for _, f := range fields {
			if !usersroles.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != usersroles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := uruo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := uruo.mutation.UserID(); ok {
		_spec.SetField(usersroles.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := uruo.mutation.AddedUserID(); ok {
		_spec.AddField(usersroles.FieldUserID, field.TypeInt64, value)
	}
	if uruo.mutation.RoleCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.RoleTable,
			Columns: []string{usersroles.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.RoleIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.RoleTable,
			Columns: []string{usersroles.RoleColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if uruo.mutation.TeamsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.TeamsTable,
			Columns: []string{usersroles.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := uruo.mutation.TeamsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   usersroles.TeamsTable,
			Columns: []string{usersroles.TeamsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(role.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(uruo.modifiers...)
	_node = &UsersRoles{config: uruo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, uruo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{usersroles.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	uruo.mutation.done = true
	return _node, nil
}
