// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"rbac/ent/role"
	"rbac/ent/usersroles"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// UsersRoles is the model entity for the UsersRoles schema.
type UsersRoles struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// RoleID holds the value of the "role_id" field.
	RoleID int64 `json:"role_id,omitempty"`
	// TeamID holds the value of the "team_id" field.
	TeamID int64 `json:"team_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UsersRolesQuery when eager-loading is set.
	Edges        UsersRolesEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UsersRolesEdges holds the relations/edges for other nodes in the graph.
type UsersRolesEdges struct {
	// Role holds the value of the role edge.
	Role *Role `json:"role,omitempty"`
	// Teams holds the value of the teams edge.
	Teams *Role `json:"teams,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// RoleOrErr returns the Role value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsersRolesEdges) RoleOrErr() (*Role, error) {
	if e.loadedTypes[0] {
		if e.Role == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: role.Label}
		}
		return e.Role, nil
	}
	return nil, &NotLoadedError{edge: "role"}
}

// TeamsOrErr returns the Teams value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UsersRolesEdges) TeamsOrErr() (*Role, error) {
	if e.loadedTypes[1] {
		if e.Teams == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: role.Label}
		}
		return e.Teams, nil
	}
	return nil, &NotLoadedError{edge: "teams"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsersRoles) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usersroles.FieldID, usersroles.FieldUserID, usersroles.FieldRoleID, usersroles.FieldTeamID:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsersRoles fields.
func (ur *UsersRoles) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usersroles.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ur.ID = int64(value.Int64)
		case usersroles.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				ur.UserID = value.Int64
			}
		case usersroles.FieldRoleID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				ur.RoleID = value.Int64
			}
		case usersroles.FieldTeamID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field team_id", values[i])
			} else if value.Valid {
				ur.TeamID = value.Int64
			}
		default:
			ur.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsersRoles.
// This includes values selected through modifiers, order, etc.
func (ur *UsersRoles) Value(name string) (ent.Value, error) {
	return ur.selectValues.Get(name)
}

// QueryRole queries the "role" edge of the UsersRoles entity.
func (ur *UsersRoles) QueryRole() *RoleQuery {
	return NewUsersRolesClient(ur.config).QueryRole(ur)
}

// QueryTeams queries the "teams" edge of the UsersRoles entity.
func (ur *UsersRoles) QueryTeams() *RoleQuery {
	return NewUsersRolesClient(ur.config).QueryTeams(ur)
}

// Update returns a builder for updating this UsersRoles.
// Note that you need to call UsersRoles.Unwrap() before calling this method if this UsersRoles
// was returned from a transaction, and the transaction was committed or rolled back.
func (ur *UsersRoles) Update() *UsersRolesUpdateOne {
	return NewUsersRolesClient(ur.config).UpdateOne(ur)
}

// Unwrap unwraps the UsersRoles entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ur *UsersRoles) Unwrap() *UsersRoles {
	_tx, ok := ur.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsersRoles is not a transactional entity")
	}
	ur.config.driver = _tx.drv
	return ur
}

// String implements the fmt.Stringer.
func (ur *UsersRoles) String() string {
	var builder strings.Builder
	builder.WriteString("UsersRoles(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ur.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", ur.UserID))
	builder.WriteString(", ")
	builder.WriteString("role_id=")
	builder.WriteString(fmt.Sprintf("%v", ur.RoleID))
	builder.WriteString(", ")
	builder.WriteString("team_id=")
	builder.WriteString(fmt.Sprintf("%v", ur.TeamID))
	builder.WriteByte(')')
	return builder.String()
}

// UsersRolesSlice is a parsable slice of UsersRoles.
type UsersRolesSlice []*UsersRoles
