server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
db: host=10.2.8.175 port=5432 user=rbac dbname=rbac password=eheeph4ahngoh-J
nats: nats://10.2.4.6:4222
discovery:
  iam: discovery:///iam
  iam_timeout: 30s
  tenants: discovery:///tenants
  tenants_timeout: 30s
