server:
  http:
    addr: 0.0.0.0:8000
    timeout: 30s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 30s
consul:
  address: consul:8500
  path: app/media/
vault:
  address: vault:8200
  token: myroot
db:
  address: host=media_db port=54404 user=me dbname=api password=password sslmode=disable
discovery:
  iam: discovery:///iam
  iam_timeout: 30s
