// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"gitlab.calendaria.team/services/rbac/internal/biz"
	"gitlab.calendaria.team/services/rbac/internal/conf"
	"gitlab.calendaria.team/services/rbac/internal/data"
	"gitlab.calendaria.team/services/rbac/internal/server"
	"gitlab.calendaria.team/services/rbac/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(bootstrap *conf.Bootstrap, logger log.Logger) (*kratos.App, func(), error) {
	config, err := data.NewConfig(bootstrap)
	if err != nil {
		return nil, nil, err
	}
	jwtProcessor, err := data.NewJwtProcessor(config)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(bootstrap, logger)
	if err != nil {
		return nil, nil, err
	}
	roleRepo := data.NewRoleRepo(dataData)
	rolesUsecase, err := biz.NewRolesUsecase(logger, jwtProcessor, roleRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	rolesService := service.NewRolesService(rolesUsecase)
	permissionRepo := data.NewPermissionRepo(dataData)
	permissionsUsecase, err := biz.NewPermissionUsecase(logger, jwtProcessor, permissionRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	permissionsService := service.NewPermissionsService(permissionsUsecase)
	teamsRepo := data.NewTeamsRepo(dataData)
	teamsUsecase, err := biz.NewTeamsUsecase(logger, config, jwtProcessor, teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	teamsService := service.NewTeamsService(teamsUsecase)
	teamIdentityRoleRepo := data.NewTeamIdentityRoleRepo(dataData)
	teamIdentityUsecase, err := biz.NewTeamIdentityUsecase(logger, config, jwtProcessor, teamIdentityRoleRepo, roleRepo, teamsRepo)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	teamIdentityRoleService := service.NewTeamIdentityRoleService(teamIdentityUsecase)
	checkPermissionsService := service.NewCheckPermissionsService(teamIdentityUsecase)
	grpcServer := server.NewGRPCServer(bootstrap, logger, jwtProcessor, rolesService, permissionsService, teamsService, teamIdentityRoleService, checkPermissionsService)
	httpServer := server.NewHTTPServer(bootstrap, logger, jwtProcessor, rolesService, permissionsService, teamsService, teamIdentityRoleService, checkPermissionsService)
	app := newApp(logger, config, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
