// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.7.1
// - protoc             v4.24.4
// source: api/check-permissions/v1/check-permissions.proto

package check_permissions_v1

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationCheckPermissionsCheckPermissions = "/api.check_permissions.v1.CheckPermissions/CheckPermissions"

type CheckPermissionsHTTPServer interface {
	CheckPermissions(context.Context, *CheckPermissionsRequest) (*CheckPermissionsReply, error)
}

func RegisterCheckPermissionsHTTPServer(s *http.Server, srv CheckPermissionsHTTPServer) {
	r := s.Route("/")
	r.POST("/v1/check-permission", _CheckPermissions_CheckPermissions0_HTTP_Handler(srv))
}

func _CheckPermissions_CheckPermissions0_HTTP_Handler(srv CheckPermissionsHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CheckPermissionsRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationCheckPermissionsCheckPermissions)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CheckPermissions(ctx, req.(*CheckPermissionsRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CheckPermissionsReply)
		return ctx.Result(200, reply)
	}
}

type CheckPermissionsHTTPClient interface {
	CheckPermissions(ctx context.Context, req *CheckPermissionsRequest, opts ...http.CallOption) (rsp *CheckPermissionsReply, err error)
}

type CheckPermissionsHTTPClientImpl struct {
	cc *http.Client
}

func NewCheckPermissionsHTTPClient(client *http.Client) CheckPermissionsHTTPClient {
	return &CheckPermissionsHTTPClientImpl{client}
}

func (c *CheckPermissionsHTTPClientImpl) CheckPermissions(ctx context.Context, in *CheckPermissionsRequest, opts ...http.CallOption) (*CheckPermissionsReply, error) {
	var out CheckPermissionsReply
	pattern := "/v1/check-permission"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationCheckPermissionsCheckPermissions))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, err
}
