INSERT INTO "permission_groups" ("id", "name", "app_id") VALUES
  ('admin.permission', 'Permission', 'admin'),
  ('admin.role', 'Role', 'admin'),
  ('admin.role_system', 'System Role', 'admin'),
  ('admin.team', 'Team', 'admin'),
  ('admin.tenant', 'Tenant', 'admin'),
  ('admin.group', 'Group', 'admin'),
  ('admin.member', 'Member', 'admin'),
  ('admin.invite', 'Member Invite', 'admin');

INSERT INTO "permissions" ("id", "group_id", "name", "description", "app_id", "fields") VALUES
  ('admin.permission.create', 'admin.permission', 'Permission Create', '', 'admin', '[]'),
  ('admin.permission.read', 'admin.permission', 'Permission Read', '', 'admin', '[]'),
  ('admin.permission.update', 'admin.permission', 'Permission Update', '', 'admin', '[]'),
  ('admin.permission.delete', 'admin.permission', 'Permission Delete', '', 'admin', '[]'),
  ('admin.role.create', 'admin.role', 'Role Create', '', 'admin', '[]'),
  ('admin.role.read', 'admin.role', 'Role Read', '', 'admin', '[]'),
  ('admin.role.update', 'admin.role', 'Role Update', '', 'admin', '[]'),
  ('admin.role.delete', 'admin.role', 'Role Delete', '', 'admin', '[]'),
  ('admin.role_system.create', 'admin.role_system', 'System Role Create', '', 'admin', '[]'),
  ('admin.role_system.update', 'admin.role_system', 'System Role Update', '', 'admin', '[]'),
  ('admin.role_system.delete', 'admin.role_system', 'System Role Delete', '', 'admin', '[]'),
  ('admin.team.create', 'admin.team', 'Team Create', '', 'admin', '[]'),
  ('admin.team.read', 'admin.team', 'Team Read', '', 'admin', '[]'),
  ('admin.team.update', 'admin.team', 'Team Update', '', 'admin', '[]'),
  ('admin.team.delete', 'admin.team', 'Team Delete', '', 'admin', '[]'),
  ('admin.role.assign', 'admin.role', 'Assign Role', '', 'admin', '[]'),
  ('admin.tenant.update', 'admin.tenant', 'Tenant Update', '', 'admin', '[]'),
  ('admin.tenant.delete', 'admin.tenant', 'Tenant Delete', '', 'admin', '[]'),
  ('admin.group.create', 'admin.group', 'Group Create', '', 'admin', '[]'),
  ('admin.group.read', 'admin.group', 'Group Read', '', 'admin', '[]'),
  ('admin.group.update', 'admin.group', 'Group Update', '', 'admin', '[]'),
  ('admin.group.delete', 'admin.group', 'Group Delete', '', 'admin', '[]'),
  ('admin.member.read', 'admin.member', 'Member Read', '', 'admin', '[]'),
  ('admin.member.delete', 'admin.member', 'Member Delete', '', 'admin', '[]'),
  ('admin.invite.create', 'admin.invite', 'Member Invite Create', '', 'admin', '[]'),
  ('admin.invite.read', 'admin.invite', 'Member Invite Read', '', 'admin', '[]'),
  ('admin.invite.delete', 'admin.invite', 'Member Invite Delete', '', 'admin', '[]');