INSERT INTO "permissions" ("id", "name", "description", "app_id", "fields") VALUES
  ('admin.permission.create', 'Permission Create', '', 'admin', '[]')
, ('admin.permission.read', 'Permission Read', '', 'admin', '[]')
, ('admin.permission.update', 'Permission Update', '', 'admin', '[]')
, ('admin.permission.delete', 'Permission Delete', '', 'admin', '[]')
, ('admin.role.create', 'Role Create', '', 'admin', '[]')
, ('admin.role.read', 'Role Read', '', 'admin', '[]')
, ('admin.role.update', 'Role Update', '', 'admin', '[]')
, ('admin.role.delete', 'Role Delete', '', 'admin', '[]')
, ('admin.role_system.create', 'System Role Create', '', 'admin', '[]')
, ('admin.role_system.update', 'System Role Update', '', 'admin', '[]')
, ('admin.role_system.delete', 'System Role Delete', '', 'admin', '[]')
, ('admin.team.create', 'Team Create', '', 'admin', '[]')
, ('admin.team.read', 'Team Read', '', 'admin', '[]')
, ('admin.team.update', 'Team Update', '', 'admin', '[]')
, ('admin.team.delete', 'Team Delete', '', 'admin', '[]')
, ('admin.role.assign', 'Assign Role', '', 'admin', '[]')
, ('admin.tenant.update', 'Tenant Update', '', 'admin', '[]')
, ('admin.tenant.delete', 'Tenant Delete', '', 'admin', '[]')
, ('admin.group.create', 'Group Create', '', 'admin', '[]')
, ('admin.group.read', 'Group Read', '', 'admin', '[]')
, ('admin.group.update', 'Group Update', '', 'admin', '[]')
, ('admin.group.delete', 'Group Delete', '', 'admin', '[]')
, ('admin.member.read', 'Member Read', '', 'admin', '[]')
, ('admin.member.delete', 'Member Delete', '', 'admin', '[]')
, ('admin.invite.create', 'Member Invite Create', '', 'admin', '[]')
, ('admin.invite.read', 'Member Invite Read', '', 'admin', '[]')
, ('admin.invite.delete', 'Member Invite Delete', '', 'admin', '[]')
;