-- Create "permission_groups" table
CREATE TABLE "permission_groups" ("id" character varying NOT NULL, "app_id" character varying NOT NULL, "name" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "permissions" table
CREATE TABLE "permissions" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "app_id" character varying NOT NULL, "fields" jsonb NULL, "group_id" character varying NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "permissions_permission_groups_permissions" FOREIGN KEY ("group_id") REFERENCES "permission_groups" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "roles" table
CREATE TABLE "roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "tenant_id" bigint NOT NULL DEFAULT 0, "is_system" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "role_permissions" table
CREATE TABLE "role_permissions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" bigint NOT NULL DEFAULT 0, "deny" boolean NOT NULL DEFAULT false, "fields" jsonb NOT NULL, "permission_id" character varying NOT NULL, "role_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "role_permissions_permissions_roles" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "role_permissions_roles_permissions" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "rolepermission_role_id_permission_id" to table: "role_permissions"
CREATE UNIQUE INDEX "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
-- Create "teams" table
CREATE TABLE "teams" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "deleted_at" timestamptz NULL, "tenant_id" bigint NOT NULL, "parents_ids" bigint[] NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "parent_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "teams_teams_children" FOREIGN KEY ("parent_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create "team_identity_roles" table
CREATE TABLE "team_identity_roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" bigint NOT NULL, "identity_id" character varying NOT NULL DEFAULT '', "role_id" bigint NOT NULL, "team_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "team_identity_roles_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "team_identity_roles_teams_team" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "teamidentityrole_tenant_id_role_id_identity_id" to table: "team_identity_roles"
CREATE UNIQUE INDEX "teamidentityrole_tenant_id_role_id_identity_id" ON "team_identity_roles" ("tenant_id", "role_id", "identity_id") WHERE (team_id IS NULL);
-- Create index "teamidentityrole_tenant_id_role_id_identity_id_team_id" to table: "team_identity_roles"
CREATE UNIQUE INDEX "teamidentityrole_tenant_id_role_id_identity_id_team_id" ON "team_identity_roles" ("tenant_id", "role_id", "identity_id", "team_id") WHERE (team_id IS NOT NULL);
