-- Create "permissions" table
CREATE TABLE "permissions" ("id" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "app_id" character varying NOT NULL, "fields" jsonb NULL, "role_permissions" bigint NULL, PRIMARY KEY ("id"));
-- Create "role_permissions" table
CREATE TABLE "role_permissions" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" bigint NOT NULL DEFAULT 0, "deny" boolean NOT NULL DEFAULT false, "fields" jsonb NOT NULL, "role_id" bigint NOT NULL, "permission_id" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create index "rolepermission_role_id_permission_id" to table: "role_permissions"
CREATE UNIQUE INDEX "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
-- Create "roles" table
CREATE TABLE "roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "deleted_at" timestamptz NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "tenant_id" bigint NOT NULL, "is_system" boolean NOT NULL DEFAULT false, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "permission_roles" character varying NULL, PRIMARY KEY ("id"));
-- Create "team_identity_roles" table
CREATE TABLE "team_identity_roles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" bigint NOT NULL, "identity_id" character varying NOT NULL DEFAULT '', "role_id" bigint NOT NULL, "team_id" bigint NULL DEFAULT 0, PRIMARY KEY ("id"));
-- Create "teams" table
CREATE TABLE "teams" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "deleted_at" timestamptz NULL, "tenant_id" bigint NOT NULL, "parents_ids" bigint[] NULL, "name" character varying NOT NULL, "description" character varying NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "parent_id" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "teams_teams_children" FOREIGN KEY ("parent_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Modify "permissions" table
ALTER TABLE "permissions" ADD CONSTRAINT "permissions_roles_permissions" FOREIGN KEY ("role_permissions") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "role_permissions" table
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permissions_permission" FOREIGN KEY ("permission_id") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "role_permissions_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;
-- Modify "roles" table
ALTER TABLE "roles" ADD CONSTRAINT "roles_permissions_roles" FOREIGN KEY ("permission_roles") REFERENCES "permissions" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Modify "team_identity_roles" table
ALTER TABLE "team_identity_roles" ADD CONSTRAINT "team_identity_roles_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, ADD CONSTRAINT "team_identity_roles_teams_team" FOREIGN KEY ("team_id") REFERENCES "teams" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
