-- Create "resource_types" table
CREATE TABLE "resource_types" ("id" character varying NOT NULL, "description" character varying NULL DEFAULT '', PRIMARY KEY ("id"));
-- Modify "roles" table
ALTER TABLE "roles" ADD COLUMN "resource_type_roles" character varying NULL, ADD CONSTRAINT "roles_resource_types_roles" FOREIGN KEY ("resource_type_roles") REFERENCES "resource_types" ("id") ON UPDATE NO ACTION ON DELETE SET NULL;
-- Create "resource_accesses" table
CREATE TABLE "resource_accesses" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "tenant_id" bigint NOT NULL, "resource_id" bigint NULL, "identity_id" character varying NOT NULL DEFAULT '', "role_id" bigint NOT NULL, "resource_type" character varying NULL, PRIMARY KEY ("id"), CONSTRAINT "resource_accesses_resource_types_type" FOREIGN KEY ("resource_type") REFERENCES "resource_types" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "resource_accesses_roles_role" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "resourceaccess_tenant_id_role_id_identity_id" to table: "resource_accesses"
CREATE UNIQUE INDEX "resourceaccess_tenant_id_role_id_identity_id" ON "resource_accesses" ("tenant_id", "role_id", "identity_id") WHERE (resource_id IS NULL);
-- Create index "resourceaccess_tenant_id_role_id_identity_id_resource_type_" to table: "resource_accesses"
CREATE UNIQUE INDEX "resourceaccess_tenant_id_role_id_identity_id_resource_type_" ON "resource_accesses" ("tenant_id", "role_id", "identity_id", "resource_type", "resource_id") WHERE (resource_id IS NOT NULL);
