// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// UsersRoles is the predicate function for usersroles builders.
type UsersRoles func(*sql.Selector)
